# --- !Ups

CREATE SCHEMA "APP";

CREATE SCHEMA "STASH";

CREATE TABLE   "STASH"."PROFILE_DATA"
(
  "ID" bigserial,
  "CATEGORY" character varying(50) NOT NULL,
  "GLOBAL_CODE" character varying(100) NOT NULL,
  "INTERNAL_CODE" character varying(100) NOT NULL,
  "DESCRIPTION" character varying(1024),
  "ATTORNEY" character varying(100),
  "BIO_MATERIAL_TYPE" character varying(50),
  "COURT" character varying(100),
  "CRIME_INVOLVED" character varying(50),
  "CRIME_TYPE" character varying(50),
  "CRIMINAL_CASE" character varying(50),
  "INTERNAL_SAMPLE_CODE" character varying(50) NOT NULL,
  "ASSIGNEE" character varying(50) NOT NULL,
  "LABORATORY" character varying(50) NOT NULL,
  "PROFILE_EXPIRATION_DATE" date,
  "RESPONSIBLE_GENETICIST" character varying(50),
  "SAMPLE_DATE" date,
  "SAMPLE_ENTRY_DATE" date,
  "DELETED" boolean NOT NULL DEFAULT false,
  "DELETED_SOLICITOR" character varying(100),
  "DELETED_MOTIVE" character varying(8192),
  CONSTRAINT "STASH_PROFILE_DATA_ID_PKEY" PRIMARY KEY ("ID"),
  CONSTRAINT "STASH_PROFILE_DATA_GLOBAL_CODE_KEY" UNIQUE ("GLOBAL_CODE")
);

CREATE TABLE "STASH"."PROFILE_DATA_FILIATION"
(
   "ID" bigserial, 
   "PROFILE_DATA" character varying(100) NOT NULL,
   "FULL_NAME" character varying(150) NOT NULL, 
   "NICKNAME" character varying(150) NOT NULL, 
   "BIRTHDAY" date NOT NULL,
   "BIRTH_PLACE" character varying(100) NOT NULL, 
   "NATIONALITY" character varying(50) NOT NULL, 
   "IDENTIFICATION" character varying(100) NOT NULL, 
   "IDENTIFICATION_ISSUING_AUTHORITY" character varying(100) NOT NULL, 
   "ADDRESS" character varying(100) NOT NULL, 
   CONSTRAINT "STASH_PROFILE_DATA_FILIATION_PK" PRIMARY KEY ("ID"),
   CONSTRAINT "STASHPROFILE_DATA_FILIATION_CODE_KEY" UNIQUE ("PROFILE_DATA"),
   CONSTRAINT "STASHPROFILE_DATA_FILIATION_FK" FOREIGN KEY ("PROFILE_DATA")
      REFERENCES "STASH"."PROFILE_DATA" ("GLOBAL_CODE")
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE "STASH"."PROFILE_DATA_FILIATION_RESOURCES"
(
  "ID" bigserial,
  "PROFILE_DATA_FILIATION" character varying(100) NOT NULL,
  "RESOURCE" oid NOT NULL,
  "RESOURCE_TYPE" character varying(1) NOT NULL,
  CONSTRAINT "STASH_PROFILE_DATA_FILIATION_RESOURCE_PK" PRIMARY KEY ("ID" ),
  CONSTRAINT "STASH_PROFILE_DATA_FILIATION_RESOURSE_FK" FOREIGN KEY ("PROFILE_DATA_FILIATION")
      REFERENCES "STASH"."PROFILE_DATA_FILIATION" ("PROFILE_DATA")
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE   "APP"."GROUP"
(
  "ID" character varying(50) NOT NULL,
  "NAME" character varying(100) NOT NULL,
  "DESCRIPTION" character varying(1024),
  CONSTRAINT "GROUP_ID_PKEY" PRIMARY KEY ("ID"),
  CONSTRAINT "GROUP_NAME_KEY" UNIQUE ("NAME")
);

COMMENT ON TABLE   "APP"."GROUP"
  IS 'Categories are agrupated by groups';

CREATE TABLE   "APP"."CATEGORY"
(
  "ID" character varying(50) NOT NULL,
  "GROUP" character varying(50) NOT NULL,
  "NAME" character varying(100) NOT NULL,
  "DESCRIPTION" character varying(1024),
  "MIXTURE" boolean NOT NULL DEFAULT false,
  "COLLECTION_URI" character varying(500) NOT NULL DEFAULT '',
  "DRAFT_URI" character varying(500) NOT NULL DEFAULT '',
  "FILIATION_DATA" boolean NOT NULL DEFAULT false,
  "REPLICATE" boolean NOT NULL DEFAULT true,
  "PEDIGREE_ASSOCIATION" boolean NOT NULL DEFAULT false,
  "MIN_LOCUS_PER_PROFILE" character varying(1024) NOT NULL DEFAULT 'K',
  "MAX_SHORTAGE_DEVIATED_LOCI" character varying(1024) NOT NULL DEFAULT '0',
  "MAX_OVERAGE_DEVIATED_LOCI" character varying(1024) NOT NULL DEFAULT '0',
  CONSTRAINT "CATEGORY_ID_PKEY" PRIMARY KEY ("ID"),
  CONSTRAINT "CATEGORY_GROUP_FKEY" FOREIGN KEY ("GROUP")
      REFERENCES "APP"."GROUP" ("ID")
      ON UPDATE CASCADE ON DELETE RESTRICT
);

COMMENT ON TABLE   "APP"."CATEGORY"
  IS 'Bilogic samples belogs to certain Category which defines specific bussines rules';

CREATE TABLE "APP"."CATEGORY_ALIAS"
(
  "ALIAS" character varying(100) NOT NULL, 
  "CATEGORY" character varying(50) NOT NULL, 
  CONSTRAINT "CATEGORY_ALIAS_PK" PRIMARY KEY ("ALIAS"), 
  CONSTRAINT "CATEGORY_ALIAS_FK" FOREIGN KEY ("CATEGORY") 
	REFERENCES "APP"."CATEGORY" ("ID") 
	ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE   "APP"."CATEGORY_ASSOCIATION"
(
  "CATEGORY" character varying(50) NOT NULL,
  "CATEGORY_RELATED" character varying(50) NOT NULL,
  "MISMATCHS" int NOT NULL DEFAULT 0,
  CONSTRAINT "CATEGORY_ASSOCIATION_PKEY" PRIMARY KEY ("CATEGORY", "CATEGORY_RELATED"),
  CONSTRAINT "CATEGORY_ASSOCIATION_CATEGORY_FKEY" FOREIGN KEY ("CATEGORY")
      REFERENCES "APP"."CATEGORY" ("ID")
      ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT "CATEGORY_ASSOCIATION_CATEGORY_RELATED_FKEY" FOREIGN KEY ("CATEGORY_RELATED")
      REFERENCES "APP"."CATEGORY" ("ID")
      ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE   "APP"."CATEGORY_MATCHING"
(
  "CATEGORY" character varying(50) NOT NULL,
  "CATEGORY_RELATED" character varying(50) NOT NULL,
  "PRIORITY" int NOT NULL DEFAULT 1,
  "MINIMUM_STRINGENCY" character varying(50) NULL,
  "FAIL_ON_MATCH" boolean NULL DEFAULT false,
  "FORWARD_TO_UPPER" boolean NULL DEFAULT false,
  "MATCHING_ALGORITHM" character varying(1024) NOT NULL DEFAULT 'ENFSI',
  "MIN_LOCUS_MATCH" int NOT NULL DEFAULT 10,
  "MISMATCHS_ALLOWED" int NOT NULL DEFAULT 0,
  CONSTRAINT "CATEGORY_MATCHING_PKEY" PRIMARY KEY ("CATEGORY", "CATEGORY_RELATED"),
  CONSTRAINT "CATEGORY_MATCHING_CATEGORY_FKEY" FOREIGN KEY ("CATEGORY")
      REFERENCES "APP"."CATEGORY" ("ID")
      ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT "CATEGORY_MATCHING_CATEGORY_RELATED_FKEY" FOREIGN KEY ("CATEGORY_RELATED")
      REFERENCES "APP"."CATEGORY" ("ID")
      ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE "APP"."BATCH_PROTO_PROFILE"
(
   "ID" bigserial NOT NULL,
   "USER" character varying(50) NOT NULL, 
   "DATE" date NOT NULL,
   CONSTRAINT "PROTO_PROFILE_BATCH_PK" PRIMARY KEY ("ID")
);

CREATE SEQUENCE "APP"."PROTO_PROFILE_DATA_GLOBAL_CODE_seq"
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1100
  CACHE 1;

CREATE TABLE "APP"."PROTO_PROFILE"
(
   "ID" bigserial NOT NULL,
   "SAMPLE_NAME" character varying(100) NOT NULL, 
   "ID_BATCH" bigint NOT NULL,
   "ASSIGNEE" character varying(100) NOT NULL, 
   "CATEGORY" character varying(100) NOT NULL,
   "STATUS" character varying(150) NOT NULL, 
   "PANEL" character varying(150) NOT NULL,
   "ERRORS" character varying(500),  
   "GENOTYPIFICATIONS" character varying(2000) NOT NULL,
   "MATCHING_RULES" character varying(2000) NOT NULL,
   "MISMATCHS" character varying(2000) NOT NULL,
   "REJECT_MOTIVE" character varying(2000),
   "PREEXISTENCE" character varying(100),
   "GENEMAPPER_LINE" character varying(50000) NOT NULL,  
   CONSTRAINT "PROTO_PROFILE_PK" PRIMARY KEY ("ID"),
   CONSTRAINT "PROTO_PROFILE_FK" FOREIGN KEY ("ID_BATCH")
      REFERENCES "APP"."BATCH_PROTO_PROFILE" ("ID")
      ON UPDATE NO ACTION ON DELETE NO ACTION
);


CREATE TABLE "APP"."COUNTRY"
(
   "CODE" character varying(2) NOT NULL,
   "NAME" character varying(50) NOT NULL,
   CONSTRAINT "COUNTRY_PK" PRIMARY KEY ("CODE")
);

CREATE TABLE "APP"."PROVINCE"
(
   "CODE" character varying(2) NOT NULL,
   "NAME" character varying(50) NOT NULL,
   "COUNTRY" character varying(2) NOT NULL,
   CONSTRAINT "PROV_PK" PRIMARY KEY ("CODE"),
   CONSTRAINT "COUNTRY_PROV_FK" FOREIGN KEY ("COUNTRY") REFERENCES "APP"."COUNTRY" ("CODE") ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE "APP"."LABORATORY"
(
  "CODE_NAME" character varying(20) NOT NULL,
  "NAME" character varying(100) NOT NULL,
  "COUNTRY" character varying(2) NOT NULL,
  "PROVINCE" character varying(1) NOT NULL,
  "ADDRESS" character varying(100) NOT NULL,
  "TELEPHONE" character varying(50) NOT NULL,
  "CONTACT_EMAIL" character varying(100) NOT NULL,
  "DROP_IN" double precision NOT NULL DEFAULT 0,
  "DROP_OUT" double precision NOT NULL DEFAULT 0,
  CONSTRAINT "LAB_PK" PRIMARY KEY ("CODE_NAME" ),
  CONSTRAINT "COUNTRY_FK" FOREIGN KEY ("COUNTRY") REFERENCES "APP"."COUNTRY" ("CODE") ON UPDATE NO ACTION ON DELETE NO ACTION ,
  CONSTRAINT "PROVINCE_FK" FOREIGN KEY ("PROVINCE") REFERENCES "APP"."PROVINCE" ("CODE") ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE "APP"."GENETICIST"
(
   "ID" bigserial, 
   "LABORATORY" character varying(20) NOT NULL, 
   "NAME" character varying(100) NOT NULL,
   "LASTNAME" character varying(100) NOT NULL,
   "EMAIL" character varying(100) NOT NULL,
   "TELEPHONE" character varying(100) NOT NULL, 
   CONSTRAINT "GENTICIST_PK" PRIMARY KEY ("ID"), 
   CONSTRAINT "GENETICIST_UNIQUE" UNIQUE ("LABORATORY" , "NAME", "LASTNAME" ),
   CONSTRAINT "GENTICIST_LAB_FK" FOREIGN KEY ("LABORATORY") REFERENCES "APP"."LABORATORY" ("CODE_NAME") ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE "APP"."POPULATION_BASE_FREQUENCY_NAME"
(
   "ID" bigserial,
   "NAME" character varying(50) NOT NULL,
   "THETA" double precision NOT NULL,
   "MODEL" character varying(50) NOT NULL,
   "ACTIVE" boolean NOT NULL,
   "DEFAULT" boolean NOT NULL,
   CONSTRAINT "POPULATION_BASE_FREQUENCY_NAME_PK" PRIMARY KEY ("ID"),
   CONSTRAINT "POPULATION_BASE_FREQUENCY_UNQ" UNIQUE ("NAME")
);

CREATE TABLE "APP"."POPULATION_BASE_FREQUENCY"
(
   "ID" bigserial, 
   "BASE_NAME" bigint NOT NULL, 
   "MARKER" character varying(50) NOT NULL,
   "ALLELE" double precision NOT NULL,  
   "FREQUENCY" numeric(10,8) NOT NULL, 
   CONSTRAINT "POPULATION_BASE_FREQUENCY_PK" PRIMARY KEY ("ID"),
   CONSTRAINT "POPULATION_BASE_FREQUENCY_FK" FOREIGN KEY ("BASE_NAME") 
      REFERENCES "APP"."POPULATION_BASE_FREQUENCY_NAME" ("ID") ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE "APP"."BIO_MATERIAL_TYPE"
(
  "ID" character varying(50) NOT NULL,
  "NAME" character varying(100) NOT NULL,
  "DESCRIPTION" character varying(10000),
  CONSTRAINT "BIO_MATERIAL_TYPE_PK" PRIMARY KEY ("ID" )
);

COMMENT ON TABLE "APP"."BIO_MATERIAL_TYPE"
  IS 'predefine values for biological material type';

CREATE TABLE   "APP"."PROFILE_DATA"
(
  "ID" bigserial,
  "CATEGORY" character varying(50) NOT NULL,
  "GLOBAL_CODE" character varying(100) NOT NULL,
  "INTERNAL_CODE" character varying(100) NOT NULL,
  "DESCRIPTION" character varying(1024),
  "ATTORNEY" character varying(100),
  "BIO_MATERIAL_TYPE" character varying(50),
  "COURT" character varying(100),
  "CRIME_INVOLVED" character varying(50),
  "CRIME_TYPE" character varying(50),
  "CRIMINAL_CASE" character varying(50),
  "INTERNAL_SAMPLE_CODE" character varying(50) NOT NULL,
  "ASSIGNEE" character varying(50) NOT NULL,
  "LABORATORY" character varying(50) NOT NULL,
  "PROFILE_EXPIRATION_DATE" date,
  "RESPONSIBLE_GENETICIST" character varying(50),
  "SAMPLE_DATE" date,
  "SAMPLE_ENTRY_DATE" date,
  "DELETED" boolean NOT NULL DEFAULT false,
  "DELETED_SOLICITOR" character varying(100),
  "DELETED_MOTIVE" character varying(8192),
  CONSTRAINT "PROFILE_DATA_ID_PKEY" PRIMARY KEY ("ID"),
  CONSTRAINT "PROFILE_DATA_GLOBAL_CODE_KEY" UNIQUE ("GLOBAL_CODE"),
  CONSTRAINT "PROFILE_DATA_INTERNAL_SAMPLE_CODE_KEY" UNIQUE ("INTERNAL_SAMPLE_CODE"),
  CONSTRAINT "PROFILE_DATA_BIO_MATERIAL_TYPE" FOREIGN KEY ("BIO_MATERIAL_TYPE")
      REFERENCES "APP"."BIO_MATERIAL_TYPE" ("ID")
      ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT "PROFILE_DATA_CATEGORY_FKEY" FOREIGN KEY ("CATEGORY")
      REFERENCES "APP"."CATEGORY" ("ID")
      ON UPDATE CASCADE ON DELETE RESTRICT
);

COMMENT ON TABLE   "APP"."PROFILE_DATA"
  IS 'Provenance data about the biological sample to be analysed. Each biological sample is related to a court case';

CREATE TABLE "APP"."PROFILE_DATA_FILIATION"
(
   "ID" bigserial, 
   "PROFILE_DATA" character varying(100) NOT NULL,
   "FULL_NAME" character varying(150) NOT NULL, 
   "NICKNAME" character varying(150) NOT NULL, 
   "BIRTHDAY" date NOT NULL,
   "BIRTH_PLACE" character varying(100) NOT NULL, 
   "NATIONALITY" character varying(50) NOT NULL, 
   "IDENTIFICATION" character varying(100) NOT NULL, 
   "IDENTIFICATION_ISSUING_AUTHORITY" character varying(100) NOT NULL, 
   "ADDRESS" character varying(100) NOT NULL, 
   CONSTRAINT "PROFILE_DATA_FILIATION_PK" PRIMARY KEY ("ID"),
   CONSTRAINT "PROFILE_DATA_FILIATION_CODE_KEY" UNIQUE ("PROFILE_DATA"),
   CONSTRAINT "PROFILE_DATA_FILIATION_FK" FOREIGN KEY ("PROFILE_DATA")
      REFERENCES "APP"."PROFILE_DATA" ("GLOBAL_CODE")
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE "APP"."PROFILE_DATA_FILIATION_RESOURCES"
(
  "ID" bigserial,
  "PROFILE_DATA_FILIATION" character varying(100) NOT NULL,
  "RESOURCE" oid NOT NULL,
  "RESOURCE_TYPE" character varying(1) NOT NULL,
  CONSTRAINT "PROFILE_DATA_FILIATION_RESOURCE_PK" PRIMARY KEY ("ID" ),
  CONSTRAINT "PROFILE_DATA_FILIATION_RESOURSE_FK" FOREIGN KEY ("PROFILE_DATA_FILIATION")
      REFERENCES "APP"."PROFILE_DATA_FILIATION" ("PROFILE_DATA")
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE SEQUENCE "APP"."PROFILE_DATA_GLOBAL_CODE_seq"
  INCREMENT 1
  MINVALUE 1100
  MAXVALUE 9223372036854775807
  START 1100
  CACHE 1;

COMMENT ON SEQUENCE "APP"."PROFILE_DATA_GLOBAL_CODE_seq"
  IS 'Profile data Global code is formed by a prefix plus a unique value determined by this sequence';

CREATE TABLE   "APP"."STRKIT"
(
  "ID" character varying(50) NOT NULL,
  "NAME" character varying(100) NOT NULL,
  "TYPE" character varying(20) NOT NULL,
  "LOCI_QTY" integer NOT NULL,
  "REPRESENTATIVE_PARAMETER" integer NOT NULL,
  CONSTRAINT "STRKIT_ID_PKEY" PRIMARY KEY ("ID")
);

COMMENT ON TABLE   "APP"."STRKIT"
  IS 'Short Tandem Repeat DNA Kit';

CREATE TABLE "APP"."STRKIT_ALIAS"
(
   "KIT" character varying(50) NOT NULL, 
   "ALIAS" character varying(100) NOT NULL, 
   CONSTRAINT "STRKIT_ALIAS_PK" PRIMARY KEY ("ALIAS"), 
   CONSTRAINT "STRKIT_ALIAS_FK" FOREIGN KEY ("KIT") REFERENCES "APP"."STRKIT" ("ID") ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE   "APP"."LOCUS"
(
  "ID" character varying(50) NOT NULL,
  "NAME" character varying(100) NOT NULL,
  "CHROMOSOME" character varying(2) NULL,
  "MINIMUM_ALLELES_QTY" integer NOT NULL DEFAULT 2,
  "MAXIMUM_ALLELES_QTY" integer NOT NULL DEFAULT 2,
  "CONTRIBUTORS_AFFECTED" boolean NOT NULL DEFAULT true,
  CONSTRAINT "LOCUS_ID_PKEY" PRIMARY KEY ("ID")
);

COMMENT ON TABLE   "APP"."LOCUS"
  IS 'Position in the DNA Chromosome of the mollecular markers';

CREATE TABLE "APP"."LOCUS_ALIAS"
(
  "ALIAS" character varying(100) NOT NULL, 
  "MARKER" character varying(50) NOT NULL, 
  CONSTRAINT "LOCUS_ALIAS_PK" PRIMARY KEY ("ALIAS"), 
  CONSTRAINT "LOCUS_ALIAS_FK" FOREIGN KEY ("MARKER") REFERENCES "APP"."LOCUS" ("ID") ON UPDATE NO ACTION ON DELETE NO ACTION
);


CREATE TABLE   "APP"."STRKIT_LOCUS"
(
  "STRKIT" character varying(50) NOT NULL,
  "LOCUS" character varying(50) NOT NULL,
  "FLUOROPHORE" character varying(10) NULL,
  "ORDER" int NULL,
  CONSTRAINT "STRKIT_LOCUS_PKEY" PRIMARY KEY("STRKIT", "LOCUS"),
  CONSTRAINT "STRKIT_LOCUS_STRKITS_FKEY" FOREIGN KEY ("STRKIT") REFERENCES "APP"."STRKIT" ("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT "STRKIT_LOCUS_LOCUS_FKEY" FOREIGN KEY ("LOCUS") REFERENCES "APP"."LOCUS" ("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);

COMMENT ON TABLE   "APP"."STRKIT_LOCUS"
  IS 'Stablishes which STR kit works for which locus';

CREATE TABLE "APP"."CRIME_TYPE"
(
  "ID" character varying(50) NOT NULL,
  "NAME" character varying(100) NOT NULL,
  "DESCRIPTION" character varying(1024),
  CONSTRAINT "CRIME_TYPE_ID_PKEY" PRIMARY KEY ("ID" ),
  CONSTRAINT "CRIME_TYPE_NAME_KEY" UNIQUE ("NAME" )
);

CREATE TABLE "APP"."CRIME_INVOLVED"
(
  "ID" character varying(50) NOT NULL,
  "CRIME_TYPE" character varying(50) NOT NULL,
  "NAME" character varying(100) NOT NULL,
  "DESCRIPTION" character varying(1024),
  CONSTRAINT "CRIME_INVOLVED_ID_PKEY" PRIMARY KEY ("ID" ),
  CONSTRAINT "CRIME_INVOLVED_TYPE_FKEY" FOREIGN KEY ("CRIME_TYPE")
      REFERENCES "APP"."CRIME_TYPE" ("ID")
      ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT "CRIME_TYPE_INVOLVED_KEY" UNIQUE ("ID" , "CRIME_TYPE" )
);

CREATE TABLE   "APP"."MITOCHONDRIAL_RCRS"
(
  "POSITION" int NOT NULL,
  "BASE" character varying(1) NOT NULL,
  CONSTRAINT "MITOCHONDRIAL_RCRS_PKEY" PRIMARY KEY ("POSITION")
);

COMMENT ON TABLE   "APP"."CATEGORY_MATCHING"
  IS 'Revised Cambridge Reference Sequence (rCRS) for mitochrondial match. NCBI Reference Sequence: NC_012920.1';

CREATE TABLE "APP"."COURT_CASE"
(
   "ID" bigserial, 
   "ATTORNEY" character varying(100),
   "COURT" character varying(100),
   "ASSIGNEE" character varying(50) NOT NULL,
   "INTERNAL_SAMPLE_CODE" character varying(50) NOT NULL,
   "CRIME_INVOLVED" character varying(50),
   "CRIME_TYPE" character varying(50),
   "CRIMINAL_CASE" character varying(50),
   "DELETED" boolean NOT NULL DEFAULT false,
   "FIRSTNAME" character varying(100),
   "LASTNAME" character varying(100),
   "SEX" character varying(50),
   "DATE_OF_BIRTH" date,
   "NATIONALITY" character varying(50),
   "IDENTIFICATION" character varying(50),
   "HEIGHT" character varying(50),
   "WEIGHT" character varying(50),
   "HAIRCOLOR" character varying(50),
   "SKINCOLOR" character varying(50),
   "CLOTHING" character varying(50),
   CONSTRAINT "COURT_CASE_PK" PRIMARY KEY ("ID"),
   CONSTRAINT "COURT_CASE_UNQ_INTERNAL_SAMPLE_CODE" UNIQUE ("INTERNAL_SAMPLE_CODE")
);

CREATE TABLE "APP"."PEDIGREE"
(
   "ID" bigserial NOT NULL, 
   "NAME" character varying(25) NOT NULL, 
   "DESCRIPTION" character varying(250), 
   "COURT_CASE" bigint NOT NULL,
   CONSTRAINT "PEDIGREE_COURT_CASE_FK" FOREIGN KEY ("COURT_CASE")
      REFERENCES "APP"."COURT_CASE" ("ID")
      ON UPDATE NO ACTION ON DELETE NO ACTION,
   CONSTRAINT "PEDIGREE_PK" PRIMARY KEY ("ID"), 
   CONSTRAINT "PEDIGREE_NAME_UNQ" UNIQUE ("NAME", "COURT_CASE")
);


CREATE TABLE "APP"."INDIVIDUAL"
(
  "ID" bigserial NOT NULL,
  "PEDIGREE" bigint NOT NULL,
  "ALIAS" character varying(3) NOT NULL,
  "FATHER_ID" character varying(3),
  "MOTHER_ID" character varying(3),
  "SEX" character varying(10) NOT NULL,
  "GLOBAL_CODE" character varying(25),
  "UNKNOWN" boolean NOT NULL DEFAULT false,
  CONSTRAINT "INDIVIDUAL_PK" PRIMARY KEY ("ID", "PEDIGREE"),
--  CONSTRAINT "FATHER_FK" FOREIGN KEY ("FATHER_ID", "PEDIGREE")
--      REFERENCES "APP"."INDIVIDUAL" ("ALIAS", "PEDIGREE")
--      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "GLOBAL_CODE_FK" FOREIGN KEY ("GLOBAL_CODE")
      REFERENCES "APP"."PROFILE_DATA" ("GLOBAL_CODE")
      ON UPDATE NO ACTION ON DELETE NO ACTION,
--  CONSTRAINT "MOTHER_FK" FOREIGN KEY ("MOTHER_ID", "PEDIGREE")
--      REFERENCES "APP"."INDIVIDUAL" ("ALIAS", "PEDIGREE")
--      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "PEDIGREE_FK" FOREIGN KEY ("PEDIGREE")
      REFERENCES "APP"."PEDIGREE" ("ID")
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "ALIAS_PEDIGREE_UK" UNIQUE ("ALIAS", "PEDIGREE")
);

CREATE TABLE "APP"."COURT_CASE_PROFILES"
(
   "COURT_CASE" bigint NOT NULL, 
   "GLOBAL_CODE" character varying(100)  NOT NULL, 
   CONSTRAINT "COURT_CASE_PROFILES_PK" PRIMARY KEY ("COURT_CASE", "GLOBAL_CODE"), 
   CONSTRAINT "PROFILES_FK" FOREIGN KEY ("GLOBAL_CODE") REFERENCES "APP"."PROFILE_DATA" ("GLOBAL_CODE") ON UPDATE NO ACTION ON DELETE NO ACTION
);

# --- !Downs

DROP SCHEMA "APP" CASCADE;
DROP SCHEMA "STASH" CASCADE;
