# --- !Ups

CREATE TABLE   "APP"."INFERIOR_INSTANCE_PROFILE_STATUS"
(
  "ID" bigserial,
  "STATUS" character varying(200) NOT NULL,
  CONSTRAINT "INFERIOR_INSTANCE_PROFILE_STATUS_ID_PKEY" PRIMARY KEY ("ID"),
  CONSTRAINT "INFERIOR_INSTANCE_PROFILE_STATUS_UK" UNIQUE ("STATUS")
);

CREATE TABLE "APP"."PROFILE_UPLOADED"
(
  "ID" bigserial,
  "GLOBAL_CODE" VARCHAR(100) NOT NULL
    UNIQUE,
  "STATUS" bigint,
  CONSTRAINT "PROFILE_UPLOADED_ID_PKEY" PRIMARY KEY ("ID"),
  CONSTRAINT "ID_PROFILE_DATA_UPLOADED_FKEY" FOREIGN KEY ("ID")
    REFERENCES "APP"."PROFILE_DATA" ("ID"),
  CONSTRAINT "PROFILE_UPLOADED_FK" FOREIGN KEY ("STATUS")
    REFERENCES "APP"."INFERIOR_INSTANCE_PROFILE_STATUS" ("ID")
);

# --- !Downs

DROP TABLE "APP"."PROFILE_UPLOADED";

DROP TABLE "APP"."INFERIOR_INSTANCE_PROFILE_STATUS";
