# --- !Ups

ALTER TABLE "APP"."ANALYSIS_TYPE" ADD COLUMN "MITOCHONDRIAL" BOOLEAN DEFAULT FALSE;

UPDATE "APP"."ANALYSIS_TYPE"
SET "MITOCHONDRIAL" = TRUE
WHERE "NAME" = 'MT';

DELETE FROM "APP"."STRKIT_LOCUS" WHERE "STRKIT" = 'MtGenericPrimers';
DELETE FROM "APP"."LOCUS" WHERE "TYPE" = (SELECT "ID" FROM "APP"."ANALYSIS_TYPE" WHERE "NAME" = 'MT');

INSERT INTO "APP"."LOCUS"("ID", "NAME", "CHROMOSOME", "MINIMUM_ALLELES_QTY", "MAXIMUM_ALLELES_QTY", "TYPE") VALUES
('HV1_RANGE', 'HV1 Rango', null, 2, 2, (SELECT "ID" FROM "APP"."ANALYSIS_TYPE" WHERE "NAME" = 'MT')),
('HV2_RANGE', 'HV2 Rango', null, 2, 2, (SELECT "ID" FROM "APP"."ANALYSIS_TYPE" WHERE "NAME" = 'MT')),
('HV3_RANGE', 'HV3 Rango', null, 2, 2, (SELECT "ID" FROM "APP"."ANALYSIS_TYPE" WHERE "NAME" = 'MT')),
('HV1', 'HV1', 'MT', 1, 300, (SELECT "ID" FROM "APP"."ANALYSIS_TYPE" WHERE "NAME" = 'MT')),
('HV2', 'HV2', 'MT', 1, 300, (SELECT "ID" FROM "APP"."ANALYSIS_TYPE" WHERE "NAME" = 'MT')),
('HV3', 'HV3', 'MT', 1, 300, (SELECT "ID" FROM "APP"."ANALYSIS_TYPE" WHERE "NAME" = 'MT'));

INSERT INTO "APP"."STRKIT_LOCUS"("STRKIT", "LOCUS", "ORDER") VALUES
('MtGenericPrimers', 'HV1_RANGE', 1),
('MtGenericPrimers', 'HV1', 2),
('MtGenericPrimers', 'HV2_RANGE', 3),
('MtGenericPrimers', 'HV2', 4),
('MtGenericPrimers', 'HV3_RANGE', 5),
('MtGenericPrimers', 'HV3', 6);

# --- !Downs

ALTER TABLE "APP"."ANALYSIS_TYPE" DROP COLUMN "MITOCHONDRIAL";

DELETE FROM "APP"."STRKIT_LOCUS" WHERE "STRKIT" = 'MtGenericPrimers';
DELETE FROM "APP"."LOCUS" WHERE "TYPE" = (SELECT "ID" FROM "APP"."ANALYSIS_TYPE" WHERE "NAME" = 'MT');

INSERT INTO "APP"."LOCUS"("ID", "NAME", "CHROMOSOME", "MINIMUM_ALLELES_QTY", "MAXIMUM_ALLELES_QTY", "TYPE") VALUES
('MT', 'Mt', 'MT', 1, 50, (SELECT "ID" FROM "APP"."ANALYSIS_TYPE" WHERE "NAME" = 'MT'));

INSERT INTO "APP"."STRKIT_LOCUS"("STRKIT", "LOCUS") VALUES
('MtGenericPrimers', 'MT');