# --- !Ups

CREATE TABLE "APP"."MATCH_SEND_STATUS"
(
  "ID" VARCHAR(100) ,
  "STATUS" bigint,
  CONSTRAINT "MATCH_SEND_STATUS_ID_PKEY" PRIMARY KEY ("ID"),
  CONSTRAINT "MATCH_SEND_STATUS_FK" FOREIGN KEY ("STATUS")
  REFERENCES "APP"."INFERIOR_INSTANCE_PROFILE_STATUS" ("ID")
);

# --- !Downs

DROP TABLE "APP"."MATCH_SEND_STATUS";

