# --- !Ups
ALTER TABLE "APP"."LOCUS" ADD COLUMN "MIN_ALLELE_VALUE" numeric(3,1) DEFAULT 0.0;
ALTER TABLE "APP"."LOCUS" ADD COLUMN "MAX_ALLELE_VALUE" numeric(3,1) DEFAULT 99.0;

UPDATE "APP"."LOCUS" SET "MIN_ALLELE_VALUE" = NULL, "MAX_ALLELE_VALUE" = NULL
  WHERE "CHROMOSOME" IN ('MT','XY') OR "CHROMOSOME" IS NULL;

# --- !Downs
ALTER TABLE "APP"."LOCUS" DROP COLUMN "MIN_ALLELE_VALUE";

ALTER TABLE "APP"."LOCUS" DROP COLUMN "MAX_ALLELE_VALUE";
