# --- !Ups

CREATE TABLE "APP"."COURT_CASE_DATA_FILIATION"
(
   "ID" bigserial,
   "ID_COURT_CASE" bigserial NOT NULL,
   "FIRSTNAME" character varying(100),
   "LASTNAME" character varying(100),
   "SEX" character varying(50),
   "DATE_OF_BIRTH" date,
   "DATE_OF_BIRTH_FROM" date,
   "DATE_OF_BIRTH_TO" date,
   "DATE_OF_MISSING" date,
   "NATIONALITY" character varying(50),
   "IDENTIFICATION" character varying(50),
   "HEIGHT" character varying(50),
   "WEIGHT" character varying(50),
   "HAIRCOLOR" character varying(50),
   "SKINCOLOR" character varying(50),
   "CLOTHING" character varying(50),
   CONSTRAINT "COURT_CASE_DATA_FILIATION_PK" PRIMARY KEY ("ID"),
   CONSTRAINT "COURT_CASE_DATA_FILIATION_FK" FOREIGN KEY ("ID_COURT_CASE")
      REFERENCES "APP"."COURT_CASE" ("ID")
      ON UPDATE NO ACTION ON DELETE NO ACTION
);
ALTER TABLE "APP"."CASE_TYPE" ADD COLUMN "NAME" character varying(50) NOT NULL DEFAULT 'MPI';

ALTER TABLE "APP"."CASE_TYPE" ALTER COLUMN  "NAME" DROP DEFAULT;

ALTER TABLE "APP"."COURT_CASE" DROP COLUMN "FIRSTNAME";
ALTER TABLE "APP"."COURT_CASE" DROP COLUMN "LASTNAME";
ALTER TABLE "APP"."COURT_CASE" DROP COLUMN "SEX";
ALTER TABLE "APP"."COURT_CASE" DROP COLUMN "DATE_OF_BIRTH";
ALTER TABLE "APP"."COURT_CASE" DROP COLUMN "NATIONALITY";
ALTER TABLE "APP"."COURT_CASE" DROP COLUMN "IDENTIFICATION";
ALTER TABLE "APP"."COURT_CASE" DROP COLUMN "HEIGHT";
ALTER TABLE "APP"."COURT_CASE" DROP COLUMN "WEIGHT";
ALTER TABLE "APP"."COURT_CASE" DROP COLUMN "HAIRCOLOR";
ALTER TABLE "APP"."COURT_CASE" DROP COLUMN "SKINCOLOR";
ALTER TABLE "APP"."COURT_CASE" DROP COLUMN "CLOTHING";

# --- !Downs
DROP TABLE "APP"."COURT_CASE_DATA_FILIATION";
ALTER TABLE "APP"."CASE_TYPE" DROP COLUMN "NAME";

ALTER TABLE "APP"."COURT_CASE" ADD COLUMN "FIRSTNAME" character varying(100);
ALTER TABLE "APP"."COURT_CASE" ADD COLUMN "LASTNAME" character varying(100);
ALTER TABLE "APP"."COURT_CASE" ADD COLUMN "SEX" character varying(50);
ALTER TABLE "APP"."COURT_CASE" ADD COLUMN "DATE_OF_BIRTH" DATE ;
ALTER TABLE "APP"."COURT_CASE" ADD COLUMN "NATIONALITY" character varying(50);
ALTER TABLE "APP"."COURT_CASE" ADD COLUMN "IDENTIFICATION" character varying(50);
ALTER TABLE "APP"."COURT_CASE" ADD COLUMN "HEIGHT" character varying(50);
ALTER TABLE "APP"."COURT_CASE" ADD COLUMN "WEIGHT" character varying(50);
ALTER TABLE "APP"."COURT_CASE" ADD COLUMN "HAIRCOLOR" character varying(50);
ALTER TABLE "APP"."COURT_CASE" ADD COLUMN "SKINCOLOR" character varying(50);
ALTER TABLE "APP"."COURT_CASE" ADD COLUMN "CLOTHING" character varying(50);
