# --- !Ups

ALTER TABLE "APP"."PROTO_PROFILE" ALTER  COLUMN "ERRORS" TYPE TEXT;
ALTER TABLE "APP"."PROTO_PROFILE" ALTER  COLUMN "REJECT_MOTIVE" TYPE TEXT;
ALTER TABLE "APP"."PROTO_PROFILE" ALTER  COLUMN "MATCHING_RULES" TYPE TEXT;
ALTER TABLE "APP"."PROTO_PROFILE" ALTER  COLUMN "MISMATCHS" TYPE TEXT;
ALTER TABLE "APP"."PROTO_PROFILE" ALTER  COLUMN "GENOTYPIFICATIONS" TYPE TEXT;

ALTER TABLE "APP"."CATEGORY" DROP COLUMN "MIXTURE";
ALTER TABLE "APP"."CATEGORY" ADD COLUMN "IS_REFERENCE" boolean NOT NULL default true;

UPDATE "APP"."CATEGORY"
SET "IS_REFERENCE" = false
WHERE "ID" IN ('UNICO', 'MULTIPLE', 'MULTIPLE_VICTIMA', 'PERSONALES', 'INDIVIDUONN', 'MUESTRANN');

UPDATE "APP"."PROTO_PROFILE"
SET "MATCHING_RULES" = '[]';

ALTER TABLE "APP"."CATEGORY_MATCHING" DROP CONSTRAINT "CATEGORY_MATCHING_CATEGORY_FKEY";
ALTER TABLE "APP"."CATEGORY_MATCHING" DROP CONSTRAINT "CATEGORY_MATCHING_PKEY";
ALTER TABLE "APP"."CATEGORY_MATCHING" ADD CONSTRAINT "CATEGORY_MATCHING_CATEGORY_FKEY" FOREIGN KEY ("CATEGORY")
      REFERENCES "APP"."CATEGORY" ("ID")
      ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "APP"."CATEGORY_MATCHING" ADD CONSTRAINT "CATEGORY_MATCHING_PKEY" PRIMARY KEY ("CATEGORY", "CATEGORY_RELATED", "MATCHING_ALGORITHM");

# --- !Downs

ALTER TABLE "APP"."PROTO_PROFILE" ALTER  COLUMN "ERRORS" TYPE character varying(500);
ALTER TABLE "APP"."PROTO_PROFILE" ALTER  COLUMN "REJECT_MOTIVE" TYPE character varying(2000);
ALTER TABLE "APP"."PROTO_PROFILE" ALTER  COLUMN "MATCHING_RULES" TYPE character varying(2000);
ALTER TABLE "APP"."PROTO_PROFILE" ALTER  COLUMN "MISMATCHS" TYPE character varying(2000);
ALTER TABLE "APP"."PROTO_PROFILE" ALTER  COLUMN "GENOTYPIFICATIONS" TYPE character varying(2000);

ALTER TABLE "APP"."CATEGORY" ADD COLUMN "MIXTURE" boolean NOT NULL DEFAULT false;
ALTER TABLE "APP"."CATEGORY" DROP COLUMN "IS_REFERENCE";

UPDATE "APP"."PROTO_PROFILE"
SET "MATCHING_RULES" = '{}';

-- NO ROLLBACK FOR CATEGORY_MATCHING PK