# --- !Ups

INSERT INTO "APP"."INFERIOR_INSTANCE_PROFILE_STATUS" ("ID", "STATUS") VALUES (7, 'Match pendiente de envío a instancia inferior');
INSERT INTO "APP"."INFERIOR_INSTANCE_PROFILE_STATUS" ("ID", "STATUS") VALUES (8, 'Match Enviado a instancia inferior');
INSERT INTO "APP"."INFERIOR_INSTANCE_PROFILE_STATUS" ("ID", "STATUS") VALUES (9, 'Hit Enviado a instancia inferior');
INSERT INTO "APP"."INFERIOR_INSTANCE_PROFILE_STATUS" ("ID", "STATUS") VALUES (10, 'Descarte Enviado a instancia inferior');
INSERT INTO "APP"."INFERIOR_INSTANCE_PROFILE_STATUS" ("ID", "STATUS") VALUES (11, 'Hit pendiente de envío a instancia inferior');
INSERT INTO "APP"."INFERIOR_INSTANCE_PROFILE_STATUS" ("ID", "STATUS") VALUES (12, 'Descarte pendiente de envío a instancia inferior');

CREATE TABLE "APP"."MATCH_SEND_STATUS"
(
  "ID" VARCHAR(100) ,
  "STATUS" bigint,
  CONSTRAINT "MATCH_SEND_STATUS_ID_PKEY" PRIMARY KEY ("ID"),
  CONSTRAINT "MATCH_SEND_STATUS_FK" FOREIGN KEY ("STATUS")
  REFERENCES "APP"."INFERIOR_INSTANCE_PROFILE_STATUS" ("ID")
);

# --- !Downs

DROP TABLE "APP"."MATCH_SEND_STATUS";

DELETE FROM "APP"."INFERIOR_INSTANCE_PROFILE_STATUS" WHERE "ID" = 7;
DELETE FROM "APP"."INFERIOR_INSTANCE_PROFILE_STATUS" WHERE "ID" = 8;
DELETE FROM "APP"."INFERIOR_INSTANCE_PROFILE_STATUS" WHERE "ID" = 9;
DELETE FROM "APP"."INFERIOR_INSTANCE_PROFILE_STATUS" WHERE "ID" = 10;
DELETE FROM "APP"."INFERIOR_INSTANCE_PROFILE_STATUS" WHERE "ID" = 11;
DELETE FROM "APP"."INFERIOR_INSTANCE_PROFILE_STATUS" WHERE "ID" = 12;



