# --- !Ups

ALTER TABLE "APP"."COURT_CASE" ADD COLUMN "CASE_TYPE" character varying(50);

CREATE TABLE "APP"."CASE_TYPE"
(
  "ID" character varying(50) NOT NULL,
  CONSTRAINT "CASE_TYPE_ID_PKEY" PRIMARY KEY ("ID")
);

INSERT INTO "APP"."CASE_TYPE" ("ID") VALUES ('MPI');
INSERT INTO "APP"."CASE_TYPE" ("ID") VALUES ('DVI');

ALTER TABLE "APP"."COURT_CASE" ADD CONSTRAINT "CASE_TYPE_FK" FOREIGN KEY ("CASE_TYPE")
REFERENCES "APP"."CASE_TYPE" ("ID");

# --- !Downs

ALTER TABLE "APP"."COURT_CASE" DROP COLUMN "CASE_TYPE";

DROP TABLE "APP"."CASE_TYPE";
