# --- !Ups

CREATE TABLE "APP"."COURT_CASE_PROFILE"
(
  "ID_COURT_CASE" bigint NOT NULL,
  "GLOBAL_CODE" character varying(100) NOT NULL,
  CONSTRAINT "PROFILES_COURT_CASE_PKEY" PRIMARY KEY ("GLOBAL_CODE","ID_COURT_CASE"),
  CONSTRAINT "CASE_TYPE_FK1" FOREIGN KEY ("ID_COURT_CASE") REFERENCES "APP"."COURT_CASE" ("ID"),
  CONSTRAINT "CASE_TYPE_FK2" FOREIGN KEY ("GLOBAL_CODE") REFERENCES "APP"."PROFILE_DATA" ("GLOBAL_CODE")
);


# --- !Downs

DROP TABLE "APP"."COURT_CASE_PROFILE";
