# --- !Ups

ALTER TABLE "APP"."COURT_CASE_PROFILE" ADD COLUMN "GROUPED_BY" character varying(100) ;

ALTER TABLE "APP"."COURT_CASE_PROFILE" ADD CONSTRAINT "CASE_TYPE_FK_GB"
FOREIGN KEY ("GROUPED_BY") REFERENCES "APP"."PROFILE_DATA" ("GLOBAL_CODE");

# --- !Downs

ALTER TABLE "APP"."COURT_CASE_PROFILE" DROP COLUMN "GROUPED_BY";