# --- !Ups
ALTER TABLE "APP"."COURT_CASE_PROFILE" ADD COLUMN "PROFILE_TYPE" character varying(50) NOT NULL DEFAULT 'Referencia';
ALTER TABLE "APP"."COURT_CASE_PROFILE" ALTER COLUMN "PROFILE_TYPE" DROP DEFAULT;
# --- !Downs
ALTER TABLE "APP"."COURT_CASE_PROFILE" DROP COLUMN "PROFILE_TYPE";
