# --- !Ups
ALTER TABLE "APP"."BATCH_PROTO_PROFILE" ADD COLUMN "ANALYSISTYPE" character varying(50)NOT NULL DEFAULT 'Autosomal';

# --- !Downs
ALTER TABLE "APP"."BATCH_PROTO_PROFILE" DROP COLUMN "ANALYSISTYPE";
