# --- !Ups
DELETE FROM "APP"."COURT_CASE_DATA_FILIATION";
ALTER TABLE "APP"."COURT_CASE_DATA_FILIATION" ADD COLUMN "ALIAS" CHARACTER VARYING (50) NOT NULL;
ALTER TABLE "APP"."COURT_CASE_DATA_FILIATION" ADD COLUMN "PARTICULARITIES" CHARACTER VARYING (50);
ALTER TABLE "APP"."COURT_CASE_DATA_FILIATION" ADD CONSTRAINT "COURTCASE_FILIATION_UK" UNIQUE ("ALIAS", "ID_COURT_CASE");
# --- !Downs
ALTER TABLE "APP"."COURT_CASE_DATA_FILIATION" DROP COLUMN "ALIAS";
ALTER TABLE "APP"."COURT_CASE_DATA_FILIATION" DROP COLUMN "PARTICULARITIES";
ALTER TABLE "APP"."COURT_CASE_DATA_FILIATION" DROP CONSTRAINT "COURTCASE_FILIATION_UK";