# --- !Ups
CREATE TABLE "APP"."CATEGORY_MODIFICATIONS"
(
 "From" varchar(50),
 "To" varchar(50),
 CONSTRAINT fk_from FOREIGN KEY ("From") REFERENCES "APP"."CATEGORY" ("ID"),
 CONSTRAINT fk_to FOREIGN KEY ("To") REFERENCES "APP"."CATEGORY"("ID")
);

# --- !Downs
DROP TABLE "APP"."CATEGORY_MODIFICATIONS";