# --- !Ups
ALTER TABLE "APP"."PROFILE_DATA"
    ADD COLUMN "FROM_DESKTOP_SEARCH" boolean NOT NULL DEFAULT false;
ALTER TABLE "STASH"."PROFILE_DATA"
    ADD COLUMN "FROM_DESKTOP_SEARCH" boolean NOT NULL DEFAULT false;


# --- !Downs
ALTER TABLE "APP"."PROFILE_DATA"
DROP COLUMN "FROM_DESKTOP_SEARCH";
ALTER TABLE "STASH"."PROFILE_DATA"
DROP COLUMN "FROM_DESKTOP_SEARCH";

