# --- !Ups
ALTER TABLE "APP"."CATEGORY_CONFIGURATION"
    ADD COLUMN "MULTIALLELIC" boolean NOT NULL DEFAULT false;


# --- !Downs
ALTER TABLE "APP"."CATEGORY_CONFIGURATION"
DROP COLUMN "MULTIALLELIC";