# --- !Ups

-- No se puede crear la secuencia como "smallserial" porque no lo soportan los tests

CREATE SEQUENCE "APP"."ANALYSIS_TYPE_ID_seq";
CREATE TABLE "APP"."ANALYSIS_TYPE"
(
  "ID" SMALLINT NOT NULL DEFAULT nextval('"APP"."ANALYSIS_TYPE_ID_seq"'),
  "NAME" character varying(50) NOT NULL,
  "LINKED" boolean NOT NULL default false,
  CONSTRAINT "APP_ANALYSIS_TYPE_ID_PKEY" PRIMARY KEY ("ID")
);

CREATE TABLE "APP"."LOCUS_LINK"
(
  "ID" bigserial,
  "LOCUS" character varying(50) NOT NULL,
  "LINK" character varying(50) NOT NULL,
  CONSTRAINT "APP_LOCUS_LINK_ID_PKEY" PRIMARY KEY ("ID"),
  CONSTRAINT "APP_LOCUS_LINK_1_LOCUS_FK" FOREIGN KEY ("LOCUS")
      REFERENCES "APP"."LOCUS" ("ID")
      ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT "APP_LOCUS_LINK_2_LOCUS_FK" FOREIGN KEY ("LINK")
      REFERENCES "APP"."LOCUS" ("ID")
      ON UPDATE CASCADE ON DELETE RESTRICT
);

-- Agregado de la columna "TYPE" en "LOCUS"

ALTER TABLE "APP"."LOCUS" ADD COLUMN "TYPE" smallint;

ALTER TABLE "APP"."LOCUS" ADD CONSTRAINT "LOCUS_ANALYSIS_TYPE_FKEY" FOREIGN KEY ("TYPE")
      REFERENCES "APP"."ANALYSIS_TYPE" ("ID")
      ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "APP"."LOCUS" ALTER COLUMN "TYPE" SET NOT NULL;

-- Cambio de la columna "TYPE" en "STRKIT"

ALTER TABLE "APP"."STRKIT" ADD COLUMN "TYPE_STRING" character varying(20);

ALTER TABLE "APP"."STRKIT" DROP COLUMN "TYPE";
ALTER TABLE "APP"."STRKIT" ADD COLUMN "TYPE" smallint;

ALTER TABLE "APP"."STRKIT" ADD CONSTRAINT "STRKIT_ANALYSIS_TYPE_FKEY" FOREIGN KEY ("TYPE")
      REFERENCES "APP"."ANALYSIS_TYPE" ("ID")
      ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "APP"."STRKIT" ALTER COLUMN "TYPE" SET NOT NULL;
ALTER TABLE "APP"."STRKIT" DROP COLUMN "TYPE_STRING";

# --- !Downs

ALTER TABLE "APP"."STRKIT" DROP CONSTRAINT "STRKIT_ANALYSIS_TYPE_FKEY";

ALTER TABLE "APP"."STRKIT" ADD COLUMN "TYPE_ID" smallint;

ALTER TABLE "APP"."STRKIT" DROP COLUMN "TYPE";
ALTER TABLE "APP"."STRKIT" ADD COLUMN "TYPE" character varying(20);

ALTER TABLE "APP"."STRKIT" ALTER COLUMN "TYPE" SET NOT NULL;
ALTER TABLE "APP"."STRKIT" DROP COLUMN "TYPE_ID";

ALTER TABLE "APP"."LOCUS" DROP CONSTRAINT "LOCUS_ANALYSIS_TYPE_FKEY";
ALTER TABLE "APP"."LOCUS" DROP COLUMN "TYPE";

DROP TABLE "APP"."ANALYSIS_TYPE";
DROP SEQUENCE "APP"."ANALYSIS_TYPE_ID_seq";

DROP TABLE "APP"."LOCUS_LINK";
