# --- !Ups

-- No se puede crear la secuencia como "smallserial" porque no lo soportan los tests

CREATE SEQUENCE "APP"."ANALYSIS_TYPE_ID_seq";
CREATE TABLE "APP"."ANALYSIS_TYPE"
(
  "ID" SMALLINT NOT NULL DEFAULT nextval('"APP"."ANALYSIS_TYPE_ID_seq"'),
  "NAME" character varying(50) NOT NULL,
  "LINKED" boolean NOT NULL default false,
  CONSTRAINT "APP_ANALYSIS_TYPE_ID_PKEY" PRIMARY KEY ("ID")
);

CREATE TABLE "APP"."LOCUS_LINK"
(
  "ID" bigserial,
  "LOCUS" character varying(50) NOT NULL,
  "LINK" character varying(50) NOT NULL,
  CONSTRAINT "APP_LOCUS_LINK_ID_PKEY" PRIMARY KEY ("ID"),
  CONSTRAINT "APP_LOCUS_LINK_1_LOCUS_FK" FOREIGN KEY ("LOCUS")
      REFERENCES "APP"."LOCUS" ("ID")
      ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT "APP_LOCUS_LINK_2_LOCUS_FK" FOREIGN KEY ("LINK")
      REFERENCES "APP"."LOCUS" ("ID")
      ON UPDATE CASCADE ON DELETE RESTRICT
);

INSERT INTO "APP"."ANALYSIS_TYPE"("NAME", "LINKED") VALUES
('Autosomal', false),
('Cx', true),
('Cy', false),
('MT', false);

-- Agregado de la columna "TYPE" en "LOCUS"

ALTER TABLE "APP"."LOCUS" ADD COLUMN "TYPE" smallint;

ALTER TABLE "APP"."LOCUS" ADD CONSTRAINT "LOCUS_ANALYSIS_TYPE_FKEY" FOREIGN KEY ("TYPE")
      REFERENCES "APP"."ANALYSIS_TYPE" ("ID")
      ON UPDATE CASCADE ON DELETE RESTRICT;

UPDATE "APP"."LOCUS"
SET "TYPE" = (SELECT "ID" FROM "APP"."ANALYSIS_TYPE" WHERE "NAME" = 'Autosomal');

UPDATE "APP"."LOCUS"
SET "TYPE" = (SELECT "ID" FROM "APP"."ANALYSIS_TYPE" WHERE "NAME" = 'Cx')
WHERE "ID" IN (SELECT DISTINCT SKL."LOCUS"
               FROM "APP"."STRKIT_LOCUS" SKL
               JOIN "APP"."STRKIT" SK ON SK."ID" = SKL."STRKIT"
               WHERE SK."TYPE" = 'X');

UPDATE "APP"."LOCUS"
SET "TYPE" = (SELECT "ID" FROM "APP"."ANALYSIS_TYPE" WHERE "NAME" = 'Cy')
WHERE "ID" IN (SELECT DISTINCT SKL."LOCUS"
               FROM "APP"."STRKIT_LOCUS" SKL
               JOIN "APP"."STRKIT" SK ON SK."ID" = SKL."STRKIT"
               WHERE SK."TYPE" = 'Y');

UPDATE "APP"."LOCUS"
SET "TYPE" = (SELECT "ID" FROM "APP"."ANALYSIS_TYPE" WHERE "NAME" = 'MT')
WHERE "ID" IN (SELECT DISTINCT SKL."LOCUS"
               FROM "APP"."STRKIT_LOCUS" SKL
               JOIN "APP"."STRKIT" SK ON SK."ID" = SKL."STRKIT"
               WHERE SK."TYPE" = 'MT');

ALTER TABLE "APP"."LOCUS" ALTER COLUMN "TYPE" SET NOT NULL;

-- Cambio de la columna "TYPE" en "STRKIT"

ALTER TABLE "APP"."STRKIT" ADD COLUMN "TYPE_STRING" character varying(20);

UPDATE "APP"."STRKIT"
SET "TYPE_STRING" = "TYPE";

ALTER TABLE "APP"."STRKIT" DROP COLUMN "TYPE";
ALTER TABLE "APP"."STRKIT" ADD COLUMN "TYPE" smallint;

ALTER TABLE "APP"."STRKIT" ADD CONSTRAINT "STRKIT_ANALYSIS_TYPE_FKEY" FOREIGN KEY ("TYPE")
      REFERENCES "APP"."ANALYSIS_TYPE" ("ID")
      ON UPDATE CASCADE ON DELETE RESTRICT;

UPDATE "APP"."STRKIT"
SET "TYPE" = (SELECT "ID" FROM "APP"."ANALYSIS_TYPE" WHERE "NAME" = 'Autosomal')
WHERE "TYPE_STRING" = 'Autosomal';

UPDATE "APP"."STRKIT"
SET "TYPE" = (SELECT "ID" FROM "APP"."ANALYSIS_TYPE" WHERE "NAME" = 'Cx')
WHERE "TYPE_STRING" = 'X';

UPDATE "APP"."STRKIT"
SET "TYPE" = (SELECT "ID" FROM "APP"."ANALYSIS_TYPE" WHERE "NAME" = 'Cy')
WHERE "TYPE_STRING" = 'Y';

UPDATE "APP"."STRKIT"
SET "TYPE" = (SELECT "ID" FROM "APP"."ANALYSIS_TYPE" WHERE "NAME" = 'MT')
WHERE "TYPE_STRING" = 'MT';

ALTER TABLE "APP"."STRKIT" ALTER COLUMN "TYPE" SET NOT NULL;
ALTER TABLE "APP"."STRKIT" DROP COLUMN "TYPE_STRING";

# --- !Downs

ALTER TABLE "APP"."STRKIT" DROP CONSTRAINT "STRKIT_ANALYSIS_TYPE_FKEY";

ALTER TABLE "APP"."STRKIT" ADD COLUMN "TYPE_ID" smallint;

UPDATE "APP"."STRKIT"
SET "TYPE_ID" = "TYPE";

ALTER TABLE "APP"."STRKIT" DROP COLUMN "TYPE";
ALTER TABLE "APP"."STRKIT" ADD COLUMN "TYPE" character varying(20);

UPDATE "APP"."STRKIT"
SET "TYPE" = 'Autosomal'
WHERE "TYPE_ID" = (SELECT "ID" FROM "APP"."ANALYSIS_TYPE" WHERE "NAME" = 'Autosomal');

UPDATE "APP"."STRKIT"
SET "TYPE" = 'X'
WHERE "TYPE_ID" = (SELECT "ID" FROM "APP"."ANALYSIS_TYPE" WHERE "NAME" = 'Cx');

UPDATE "APP"."STRKIT"
SET "TYPE" = 'Y'
WHERE "TYPE_ID" = (SELECT "ID" FROM "APP"."ANALYSIS_TYPE" WHERE "NAME" = 'Cy');

UPDATE "APP"."STRKIT"
SET "TYPE" = 'MT'
WHERE "TYPE_ID" = (SELECT "ID" FROM "APP"."ANALYSIS_TYPE" WHERE "NAME" = 'MT');

ALTER TABLE "APP"."STRKIT" ALTER COLUMN "TYPE" SET NOT NULL;
ALTER TABLE "APP"."STRKIT" DROP COLUMN "TYPE_ID";

ALTER TABLE "APP"."LOCUS" DROP CONSTRAINT "LOCUS_ANALYSIS_TYPE_FKEY";
ALTER TABLE "APP"."LOCUS" DROP COLUMN "TYPE";

DROP TABLE "APP"."ANALYSIS_TYPE";
DROP SEQUENCE "APP"."ANALYSIS_TYPE_ID_seq";

DROP TABLE "APP"."LOCUS_LINK";