# --- !Ups
-- This section applies the changes.

ALTER TABLE IF EXISTS "APP"."PROFILE_UPLOADED"
    ADD COLUMN "OPERATION_ORIGINATED_IN_INSTANCE" text;
ALTER TABLE IF EXISTS "APP"."PROFILE_RECEIVED"
    ADD COLUMN "OPERATION_ORIGINATED_IN_INSTANCE" text;

COMMENT ON COLUMN "APP"."PROFILE_UPLOADED"."OPERATION_ORIGINATED_IN_INSTANCE" IS 'Última operación generada en esta instancia.';
COMMENT ON COLUMN "APP"."PROFILE_RECEIVED"."OPERATION_ORIGINATED_IN_INSTANCE" IS 'Última operación generada en esta instancia.';


# --- !Downs

ALTER TABLE IF EXISTS "APP"."PROFILE_UPLOADED"
    DROP COLUMN "OPERATION_ORIGINATED_IN_INSTANCE";

ALTER TABLE IF EXISTS "APP"."PROFILE_RECEIVED"
    DROP COLUMN "OPERATION_ORIGINATED_IN_INSTANCE";