# --- !Ups
-- This section applies the changes.
ALTER TABLE IF EXISTS "APP"."PROFILE_UPLOADED"
    ADD COLUMN "DATE_UPLOADED" text;
ALTER TABLE IF EXISTS "APP"."PROFILE_RECEIVED"
    ADD COLUMN "DATE_RECEIVED" text;

COMMENT ON COLUMN "APP"."PROFILE_UPLOADED"."DATE_UPLOADED" IS 'Fecha en el que el perfil fue replicado.';
COMMENT ON COLUMN "APP"."PROFILE_RECEIVED"."DATE_RECEIVED" IS 'Fecha en la que el perfil es recibido.';


# --- !Downs

ALTER TABLE IF EXISTS "APP"."PROFILE_UPLOADED"
    DROP COLUMN "DATE_UPLOADED";

ALTER TABLE IF EXISTS "APP"."PROFILE_RECEIVED"
    DROP COLUMN "DATE_RECEIVED";