# --- !Ups
CREATE TABLE IF NOT EXISTS "APP"."PEDIGREE_MATCHING_PARAMETER" (
    "ID" BIGINT NOT NULL,
    "MAX_MENDELIAN_EXCLUSIONS" INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT "PEDIGREE_MATCHING_PARAMETER_PK" PRIMARY KEY ("ID")
);

COMMENT ON TABLE "APP"."PEDIGREE_MATCHING_PARAMETER" IS 'Parametros globales del algoritmo de matching de pedigries (fila unica, ID=1)';
COMMENT ON COLUMN "APP"."PEDIGREE_MATCHING_PARAMETER"."MAX_MENDELIAN_EXCLUSIONS" IS 'Cantidad maxima de marcadores con exclusion mendeliana que se toleran en un match de compatibilidad antes de descartarlo';

INSERT INTO "APP"."PEDIGREE_MATCHING_PARAMETER" ("ID", "MAX_MENDELIAN_EXCLUSIONS") VALUES (1, 0);

# --- !Downs

DROP TABLE IF EXISTS "APP"."PEDIGREE_MATCHING_PARAMETER";