# --- !Ups

ALTER TABLE "APP"."ANALYSIS_TYPE" DROP COLUMN "LINKED";

ALTER TABLE "APP"."LOCUS" DROP COLUMN "CONTRIBUTORS_AFFECTED";

ALTER TABLE "APP"."LOCUS_LINK" ADD COLUMN "FACTOR" double precision DEFAULT 0;
ALTER TABLE "APP"."LOCUS_LINK" ADD COLUMN "DISTANCE" double precision DEFAULT 0;

ALTER TABLE "APP"."COURT_CASE" DROP COLUMN "DELETED";
ALTER TABLE "APP"."COURT_CASE" ADD COLUMN "STATUS" CHARACTER VARYING(50) NOT NULL DEFAULT 'UnderConstruction';

ALTER TABLE "APP"."CATEGORY_CONFIGURATION" DROP COLUMN "MAX_SHORTAGE_DEVIATED_LOCI";
ALTER TABLE "APP"."CATEGORY_CONFIGURATION" ADD COLUMN "MAX_ALLELES_PER_LOCUS" SMALLINT NOT NULL DEFAULT 6;

DROP TABLE "APP"."INDIVIDUAL";

DROP TABLE "APP"."PEDIGREE";

DROP TABLE "APP"."COURT_CASE_PROFILES"

# --- !Downs

ALTER TABLE "APP"."ANALYSIS_TYPE" ADD COLUMN "LINKED" boolean NOT NULL default false;

ALTER TABLE "APP"."LOCUS" ADD COLUMN "CONTRIBUTORS_AFFECTED" boolean NOT NULL DEFAULT true;

ALTER TABLE "APP"."LOCUS_LINK" DROP COLUMN "FACTOR";
ALTER TABLE "APP"."LOCUS_LINK" DROP COLUMN "DISTANCE";

ALTER TABLE "APP"."COURT_CASE" ADD COLUMN "DELETED" boolean default false;
ALTER TABLE "APP"."COURT_CASE" DROP COLUMN "STATUS";

ALTER TABLE "APP"."CATEGORY_CONFIGURATION" ADD COLUMN "MAX_SHORTAGE_DEVIATED_LOCI" character varying(1024) NOT NULL DEFAULT '0';
ALTER TABLE "APP"."CATEGORY_CONFIGURATION" DROP COLUMN "MAX_ALLELES_PER_LOCUS";

CREATE TABLE "APP"."PEDIGREE"
(
   "ID" bigserial NOT NULL,
   "NAME" character varying(25) NOT NULL,
   "DESCRIPTION" character varying(250),
   "COURT_CASE" bigint NOT NULL,
   CONSTRAINT "PEDIGREE_COURT_CASE_FK" FOREIGN KEY ("COURT_CASE")
      REFERENCES "APP"."COURT_CASE" ("ID")
      ON UPDATE NO ACTION ON DELETE NO ACTION,
   CONSTRAINT "PEDIGREE_PK" PRIMARY KEY ("ID"),
   CONSTRAINT "PEDIGREE_NAME_UNQ" UNIQUE ("NAME", "COURT_CASE")
);

CREATE TABLE "APP"."INDIVIDUAL"
(
  "ID" bigserial NOT NULL,
  "PEDIGREE" bigint NOT NULL,
  "ALIAS" character varying(3) NOT NULL,
  "FATHER_ID" character varying(3),
  "MOTHER_ID" character varying(3),
  "SEX" character varying(10) NOT NULL,
  "GLOBAL_CODE" character varying(25),
  "UNKNOWN" boolean NOT NULL DEFAULT false,
  CONSTRAINT "INDIVIDUAL_PK" PRIMARY KEY ("ID", "PEDIGREE"),
  CONSTRAINT "GLOBAL_CODE_FK" FOREIGN KEY ("GLOBAL_CODE")
      REFERENCES "APP"."PROFILE_DATA" ("GLOBAL_CODE")
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "PEDIGREE_FK" FOREIGN KEY ("PEDIGREE")
      REFERENCES "APP"."PEDIGREE" ("ID")
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "ALIAS_PEDIGREE_UK" UNIQUE ("ALIAS", "PEDIGREE")
);

CREATE TABLE "APP"."COURT_CASE_PROFILES"
(
   "COURT_CASE" bigint NOT NULL,
   "GLOBAL_CODE" character varying(100)  NOT NULL,
   CONSTRAINT "COURT_CASE_PROFILES_PK" PRIMARY KEY ("COURT_CASE", "GLOBAL_CODE"),
   CONSTRAINT "PROFILES_FK" FOREIGN KEY ("GLOBAL_CODE") REFERENCES "APP"."PROFILE_DATA" ("GLOBAL_CODE") ON UPDATE NO ACTION ON DELETE NO ACTION
);
