# --- !Ups

CREATE TABLE "APP"."TRACE"
(
  "ID" bigserial,
  "PROFILE" character varying(100) NOT NULL,
  "USER" character varying(50) NOT NULL,
  "DATE" timestamp NOT NULL,
  "TRACE" character varying NOT NULL,
  "KIND" character varying(100) NOT NULL,
  CONSTRAINT "APP_TRACE_ID_PKEY" PRIMARY KEY ("ID")
);

ALTER TABLE "APP"."CATEGORY_CONFIGURATION"
  DROP CONSTRAINT "APP_CATEGORY_CONFIGURATION_CATEGORY_FK";
ALTER TABLE "APP"."CATEGORY_CONFIGURATION"
  ADD CONSTRAINT "APP_CATEGORY_CONFIGURATION_CATEGORY_FK" FOREIGN KEY ("CATEGORY")
    REFERENCES "APP"."CATEGORY" ("ID")
    ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "APP"."CATEGORY_ALIAS"
  DROP CONSTRAINT "CATEGORY_ALIAS_FK";
ALTER TABLE "APP"."CATEGORY_ALIAS"
  ADD CONSTRAINT "CATEGORY_ALIAS_FK" FOREIGN KEY ("CATEGORY")
	  REFERENCES "APP"."CATEGORY" ("ID")
	  ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "APP"."CATEGORY_ASSOCIATION"
  DROP CONSTRAINT "CATEGORY_ASSOCIATION_CATEGORY_FKEY";
ALTER TABLE "APP"."CATEGORY_ASSOCIATION"
  DROP CONSTRAINT "CATEGORY_ASSOCIATION_CATEGORY_RELATED_FKEY";
ALTER TABLE "APP"."CATEGORY_ASSOCIATION"
  ADD CONSTRAINT "CATEGORY_ASSOCIATION_CATEGORY_FKEY" FOREIGN KEY ("CATEGORY")
      REFERENCES "APP"."CATEGORY" ("ID")
      ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "APP"."CATEGORY_ASSOCIATION"
  ADD CONSTRAINT "CATEGORY_ASSOCIATION_CATEGORY_RELATED_FKEY" FOREIGN KEY ("CATEGORY_RELATED")
      REFERENCES "APP"."CATEGORY" ("ID")
      ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "APP"."CATEGORY_MATCHING"
  DROP CONSTRAINT "CATEGORY_MATCHING_CATEGORY_FKEY";
ALTER TABLE "APP"."CATEGORY_MATCHING"
  DROP CONSTRAINT "CATEGORY_MATCHING_CATEGORY_RELATED_FKEY";
ALTER TABLE "APP"."CATEGORY_MATCHING"
  ADD CONSTRAINT "CATEGORY_MATCHING_CATEGORY_FKEY" FOREIGN KEY ("CATEGORY")
      REFERENCES "APP"."CATEGORY" ("ID")
      ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "APP"."CATEGORY_MATCHING"
  ADD  CONSTRAINT "CATEGORY_MATCHING_CATEGORY_RELATED_FKEY" FOREIGN KEY ("CATEGORY_RELATED")
      REFERENCES "APP"."CATEGORY" ("ID")
      ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "APP"."CATEGORY_MATCHING" ADD COLUMN "CONSIDER_FOR_N" BOOLEAN NOT NULL DEFAULT TRUE;

# --- !Downs

DROP TABLE "APP"."TRACE";

ALTER TABLE "APP"."CATEGORY_CONFIGURATION"
  DROP CONSTRAINT "APP_CATEGORY_CONFIGURATION_CATEGORY_FK";
ALTER TABLE "APP"."CATEGORY_CONFIGURATION"
  ADD CONSTRAINT "APP_CATEGORY_CONFIGURATION_CATEGORY_FK" FOREIGN KEY ("CATEGORY")
    REFERENCES "APP"."CATEGORY" ("ID")
    ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "APP"."CATEGORY_ALIAS"
  DROP CONSTRAINT "CATEGORY_ALIAS_FK";
ALTER TABLE "APP"."CATEGORY_ALIAS"
  ADD CONSTRAINT "CATEGORY_ALIAS_FK" FOREIGN KEY ("CATEGORY")
	  REFERENCES "APP"."CATEGORY" ("ID")
	  ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "APP"."CATEGORY_ASSOCIATION"
  DROP CONSTRAINT "CATEGORY_ASSOCIATION_CATEGORY_FKEY";
ALTER TABLE "APP"."CATEGORY_ASSOCIATION"
  DROP CONSTRAINT "CATEGORY_ASSOCIATION_CATEGORY_RELATED_FKEY";
ALTER TABLE "APP"."CATEGORY_ASSOCIATION"
  ADD CONSTRAINT "CATEGORY_ASSOCIATION_CATEGORY_FKEY" FOREIGN KEY ("CATEGORY")
      REFERENCES "APP"."CATEGORY" ("ID")
      ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "APP"."CATEGORY_ASSOCIATION"
  ADD CONSTRAINT "CATEGORY_ASSOCIATION_CATEGORY_RELATED_FKEY" FOREIGN KEY ("CATEGORY_RELATED")
      REFERENCES "APP"."CATEGORY" ("ID")
      ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "APP"."CATEGORY_MATCHING"
  DROP CONSTRAINT "CATEGORY_MATCHING_CATEGORY_FKEY";
ALTER TABLE "APP"."CATEGORY_MATCHING"
  DROP CONSTRAINT "CATEGORY_MATCHING_CATEGORY_RELATED_FKEY";
ALTER TABLE "APP"."CATEGORY_MATCHING"
  ADD CONSTRAINT "CATEGORY_MATCHING_CATEGORY_FKEY" FOREIGN KEY ("CATEGORY")
      REFERENCES "APP"."CATEGORY" ("ID")
      ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "APP"."CATEGORY_MATCHING"
  ADD  CONSTRAINT "CATEGORY_MATCHING_CATEGORY_RELATED_FKEY" FOREIGN KEY ("CATEGORY_RELATED")
      REFERENCES "APP"."CATEGORY" ("ID")
      ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "APP"."CATEGORY_MATCHING" DROP COLUMN "CONSIDER_FOR_N";