events {}

http {
  server {
    listen 80;

    # ==========================================================
    # PASO 2: Todo el trafico va a legacy (:9000)
    # ----------------------------------------------------------
    # En el PASO 3, iremos moviendo rutas especificas a core:
    #
    #   location /login {
    #     proxy_pass http://host.docker.internal:9001/api/v2/login;
    #   }
    #
    # ==========================================================

    location / {
      proxy_pass http://host.docker.internal:9000;

      proxy_set_header Host              $host;
      proxy_set_header X-Real-IP         $remote_addr;
      proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      # Necesario para que Play reciba correctamente las cookies de sesion
      proxy_cookie_path / /;
    }
  }
}
