# Akka 
play {
  akka {
    actor {
      lrmix-context {
        fork-join-executor {
          parallelism-factor = 2.0
          parallelism-min = 4
          parallelism-max = 32
        }
      }
      slick-context {
        fork-join-executor {
          parallelism-min = 20
          parallelism-max = 30
        }
      }
      log-context {
        fork-join-executor {
          parallelism-min = 4
          parallelism-max = 10
        }
      }
      ldap-context {
        fork-join-executor {
          parallelism-min = 4
          parallelism-max = 10
        }
      }
      pedigree-context {
        fork-join-executor {
          parallelism-min = 4
          parallelism-max = 30
        }
      }
    }
  }
}

akka {
  loggers = ["akka.event.slf4j.Slf4jLogger"]
  loglevel="INFO"
  log-dead-letters-during-shutdown="off"
}
