include "play.conf"
include "genis-misc.conf"
include "storage.conf"
include "interconnect.conf"
include "akka.conf"

# Configuración para Slick puro (STR kits)
strkits-db {
  url = "jdbc:postgresql://localhost:5432/tu_db"
  driver = "org.postgresql.Driver"
  user = "tu_usuario"
  password = "tu_password"
  connectionPool = disabled
  keepAliveConnection = true
}




