# LDAP Configuration 
ldap {
  default {
    # Docker connection
    url = "localhost" 
    port = 1389
    # Docker LDAP password
    adminPassword="adminp"    
    # Docker LDAP admin DN
    adminDn = "cn=admin,dc=genis,dc=local"
    usersDn = "ou=Users,dc=genis,dc=local"
    rolesDn = "ou=Roles,dc=genis,dc=local"
    # another settings/tunning
    bindingPool.size = 10
  }
}

# Database configuration
db {
  default {
    # Docker connection
    url = "jdbc:postgresql://localhost:5432/genisdb"
    # Docker credentials
    user = "genissqladmin"
    password = "genissqladminp"
    # another settings/tunning
    driver = org.postgresql.Driver
    slickdriver = "pdgconf.ExtendedPostgresDriver"
    partitionCount = 2
    maxConnectionsPerPartition = 20
    minConnectionsPerPartition = 10
    connectionTimeout = 20 seconds
    acquireIncrement = 1
    acquireRetryAttempts = 5
    acquireRetryDelay = 5 seconds
    idleMaxAge = 10 minute
    logStatements = true
    maxConnectionAge = 1 hour
  }  
  logDb {
    # Docker connection
    url = "jdbc:postgresql://localhost:5432/genislogdb"
    # Docker credentials
    user = "genissqladmin"
    password = "genissqladminp"
    # another settings/tunning
    driver = org.postgresql.Driver
    slickdriver = "pdgconf.ExtendedPostgresDriver"
    partitionCount = 2
    maxConnectionsPerPartition = 5
    minConnectionsPerPartition = 5
    idleMaxAge = 10 minute
    logStatements = true
    maxConnectionAge = 1 hour
  }
}

# Evolutions
evolutionplugin = enabled

# Play-Slick Plugin, disable SQL schema generation from slick models 
slick.default = "DISABLED"

# Mongo configuration
mongodb {
  # Docker connection
  uri = "mongodb://localhost:27017/pdgdb"
  connection.strictUri = true
}

mongo-async-driver {
  akka {
    loglevel = WARNING
  }
}
