# --- !Ups

CREATE TABLE "APP"."MOTIVE_TYPE"
(
  "ID" bigserial,
  "DESCRIPTION" TEXT NOT NULL,
  CONSTRAINT "MOTIVE_TYPE_PKEY" PRIMARY KEY ("ID")
);

CREATE TABLE "APP"."MOTIVE"
(
  "ID" bigserial,
  "MOTIVE_TYPE" bigserial,
  "DESCRIPTION" TEXT NOT NULL,
  "FREE_TEXT" boolean,
  "DELETED" boolean,
  CONSTRAINT "MOTIVE_ID_PKEY" PRIMARY KEY ("ID"),
  CONSTRAINT "MOTIVE_TYPE_FK" FOREIGN KEY ("MOTIVE_TYPE") REFERENCES "APP"."MOTIVE_TYPE" ("ID")
);

CREATE TABLE "APP"."PROFILE_DATA_MOTIVE"
(
  "ID" BIGSERIAL,
  "ID_PROFILE_DATA" bigint,
  "DELETED_DATE" TIMESTAMP,
  "ID_DELETED_MOTIVE" bigserial,
  CONSTRAINT "PROFILE_DATA_MOTIVE_PKEY" PRIMARY KEY ("ID"),
  CONSTRAINT "PROFILE_DATA_MOTIVE_PKEY_FK" FOREIGN KEY ("ID_PROFILE_DATA") REFERENCES "APP"."PROFILE_DATA" ("ID"),
  CONSTRAINT "PROFILE_DATA_MOTIVE_PKEY_FK2" FOREIGN KEY ("ID_DELETED_MOTIVE") REFERENCES "APP"."MOTIVE" ("ID")
);

ALTER TABLE "APP"."PROTO_PROFILE" ADD COLUMN "ID_REJECT_MOTIVE" bigint NULL ;
ALTER TABLE "APP"."PROTO_PROFILE" ADD COLUMN "REJECTION_USER" TEXT;
ALTER TABLE "APP"."PROTO_PROFILE" ADD COLUMN "REJECTION_DATE" TIMESTAMP DEFAULT NULL;
ALTER TABLE "APP"."PROTO_PROFILE" ADD CONSTRAINT "REJECT_MOTIVE_FKEY"
  FOREIGN KEY ("ID_REJECT_MOTIVE") REFERENCES "APP"."MOTIVE" ("ID");

ALTER TABLE "APP"."PROFILE_UPLOADED" ADD COLUMN "MOTIVE" TEXT;

ALTER TABLE "APP"."SUPERIOR_INSTANCE_PROFILE_APPROVAL" ADD COLUMN "REJECTION_USER" TEXT;
ALTER TABLE "APP"."SUPERIOR_INSTANCE_PROFILE_APPROVAL" ADD COLUMN "REJECTION_DATE" TIMESTAMP;
ALTER TABLE "APP"."SUPERIOR_INSTANCE_PROFILE_APPROVAL" ADD COLUMN "ID_REJECT_MOTIVE" bigint;
ALTER TABLE "APP"."SUPERIOR_INSTANCE_PROFILE_APPROVAL" ADD COLUMN "REJECT_MOTIVE" TEXT;
ALTER TABLE "APP"."SUPERIOR_INSTANCE_PROFILE_APPROVAL" ADD COLUMN "DELETED" boolean;

# --- !Downs

ALTER TABLE "APP"."PROTO_PROFILE" DROP COLUMN  "ID_REJECT_MOTIVE";
ALTER TABLE "APP"."PROTO_PROFILE" DROP COLUMN  "REJECTION_USER";
ALTER TABLE "APP"."PROTO_PROFILE" DROP COLUMN  "REJECTION_DATE";
ALTER TABLE "APP"."PROFILE_UPLOADED" DROP COLUMN  "MOTIVE";

ALTER TABLE "APP"."SUPERIOR_INSTANCE_PROFILE_APPROVAL" DROP COLUMN  "REJECTION_USER";
ALTER TABLE "APP"."SUPERIOR_INSTANCE_PROFILE_APPROVAL" DROP COLUMN  "REJECTION_DATE";
ALTER TABLE "APP"."SUPERIOR_INSTANCE_PROFILE_APPROVAL" DROP COLUMN  "ID_REJECT_MOTIVE";
ALTER TABLE "APP"."SUPERIOR_INSTANCE_PROFILE_APPROVAL" DROP COLUMN  "REJECT_MOTIVE";
ALTER TABLE "APP"."SUPERIOR_INSTANCE_PROFILE_APPROVAL" DROP COLUMN  "DELETED";

DROP TABLE "APP"."PROFILE_DATA_MOTIVE";
DROP TABLE "APP"."MOTIVE";
DROP TABLE "APP"."MOTIVE_TYPE";
