# --- !Ups

ALTER TABLE "APP"."SUPERIOR_INSTANCE_PROFILE_APPROVAL" ADD COLUMN "PROFILE_ASSOCIATED" TEXT;

create table "APP"."MATCH_UPDATE_SEND_STATUS"
(
  "ID" varchar(100) not null,
  "TARGET_LAB" text not null,
  "MESSAGE" text,
  "STATUS" bigint
    constraint MATCH_UPDATE_SEND_STATUS_FK1
    references "APP"."INFERIOR_INSTANCE_PROFILE_STATUS",
  "DATE" timestamp default now(),
  constraint "MATCH_UPDATE_SEND_STATUS_ID_PKEY"
  primary key ("ID", "TARGET_LAB")
)
;

DROP TABLE IF EXISTS "APP"."MATCH_SEND_STATUS";

CREATE TABLE "APP"."MATCH_SEND_STATUS"
(
  "ID"         VARCHAR(100) NOT NULL,
  "TARGET_LAB" TEXT         NOT NULL,
  "MESSAGE"    TEXT,
  "STATUS"     BIGINT
    CONSTRAINT MATCH_SEND_STATUS_FK1
    REFERENCES "APP"."INFERIOR_INSTANCE_PROFILE_STATUS",
  "DATE"       TIMESTAMP DEFAULT now(),
  CONSTRAINT "MATCH_SEND_STATUS_ID_PKEY"
  PRIMARY KEY ("ID", "TARGET_LAB")
);

CREATE TABLE "APP"."PROFILE_SENT"
(
  "ID" bigserial,
  "LABCODE" TEXT,
  "GLOBAL_CODE" VARCHAR(100) NOT NULL,
  "STATUS" bigint,
  "MOTIVE" TEXT,
  CONSTRAINT "PROFILE_SENT_ID_PKEY" PRIMARY KEY ("ID","LABCODE"),
  CONSTRAINT "ID_PROFILE_DATA_SENT_FKEY" FOREIGN KEY ("ID")
  REFERENCES "APP"."PROFILE_DATA" ("ID"),
  CONSTRAINT "PROFILE_SENT_FK" FOREIGN KEY ("STATUS")
  REFERENCES "APP"."INFERIOR_INSTANCE_PROFILE_STATUS" ("ID")
);
# --- !Downs

ALTER TABLE "APP"."SUPERIOR_INSTANCE_PROFILE_APPROVAL" DROP COLUMN "PROFILE_ASSOCIATED";

DROP TABLE "APP"."MATCH_UPDATE_SEND_STATUS";

DROP TABLE IF EXISTS"APP"."PROFILE_SENT";
