# --- !Ups
ALTER TABLE "APP"."STRKIT_LOCUS"
DROP CONSTRAINT IF EXISTS "STRKIT_LOCUS_LOCUS_FKEY";

ALTER TABLE "APP"."STRKIT_LOCUS"
    ADD CONSTRAINT "STRKIT_LOCUS_LOCUS_FKEY"
        FOREIGN KEY ("LOCUS")
            REFERENCES "APP"."LOCUS"("ID")
            ON DELETE CASCADE;

# --- !Downs
ALTER TABLE "APP"."STRKIT_LOCUS"
DROP CONSTRAINT IF EXISTS "STRKIT_LOCUS_LOCUS_FKEY";

ALTER TABLE "APP"."STRKIT_LOCUS"
    ADD CONSTRAINT "STRKIT_LOCUS_LOCUS_FKEY"
        FOREIGN KEY ("LOCUS")
            REFERENCES "APP"."LOCUS"("ID");
