# --- !Ups

CREATE TABLE "APP"."CATEGORY_CONFIGURATION"
(
  "ID" bigserial,
  "CATEGORY" character varying(50) NOT NULL,
  "TYPE" smallint NOT NULL,
  "COLLECTION_URI" character varying(500) NOT NULL DEFAULT '',
  "DRAFT_URI" character varying(500) NOT NULL DEFAULT '',
  "MIN_LOCUS_PER_PROFILE" character varying(1024) NOT NULL DEFAULT 'K',
  "MAX_SHORTAGE_DEVIATED_LOCI" character varying(1024) NOT NULL DEFAULT '0',
  "MAX_OVERAGE_DEVIATED_LOCI" character varying(1024) NOT NULL DEFAULT '0',
  CONSTRAINT "APP_CATEGORY_CONFIGURATION_ID_PKEY" PRIMARY KEY ("ID"),
  CONSTRAINT "APP_CATEGORY_CONFIGURATION_CATEGORY_FK" FOREIGN KEY ("CATEGORY")
    REFERENCES "APP"."CATEGORY" ("ID")
    ON UPDATE CASCADE ON DELETE RESTRICT,
	CONSTRAINT "APP_CATEGORY_CONFIGURATION_ANALYSIS_TYPE_FKEY" FOREIGN KEY ("TYPE")
      REFERENCES "APP"."ANALYSIS_TYPE" ("ID")
      ON UPDATE CASCADE ON DELETE RESTRICT
);

ALTER TABLE "APP"."CATEGORY"
DROP COLUMN "COLLECTION_URI";
ALTER TABLE "APP"."CATEGORY"
DROP COLUMN "DRAFT_URI";
ALTER TABLE "APP"."CATEGORY"
DROP COLUMN "MIN_LOCUS_PER_PROFILE";
ALTER TABLE "APP"."CATEGORY"
DROP COLUMN "MAX_SHORTAGE_DEVIATED_LOCI";
ALTER TABLE "APP"."CATEGORY"
DROP COLUMN "MAX_OVERAGE_DEVIATED_LOCI";

ALTER TABLE "APP"."CATEGORY_ASSOCIATION"
DROP CONSTRAINT "CATEGORY_ASSOCIATION_PKEY";
ALTER TABLE "APP"."CATEGORY_ASSOCIATION"
ADD COLUMN "ID" bigserial;
ALTER TABLE "APP"."CATEGORY_ASSOCIATION"
ADD COLUMN "TYPE" smallint;
ALTER TABLE "APP"."CATEGORY_ASSOCIATION"
ADD CONSTRAINT "CATEGORY_ASSOCIATION_PKEY" PRIMARY KEY ("ID");
ALTER TABLE "APP"."CATEGORY_ASSOCIATION"
ADD CONSTRAINT "APP_CATEGORY_ASSOCIATION_ANALYSIS_TYPE_FKEY" FOREIGN KEY ("TYPE")
      REFERENCES "APP"."ANALYSIS_TYPE" ("ID")
      ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "APP"."CATEGORY_MATCHING"
DROP CONSTRAINT "CATEGORY_MATCHING_PKEY";
ALTER TABLE "APP"."CATEGORY_MATCHING"
ADD COLUMN "ID" bigserial;
ALTER TABLE "APP"."CATEGORY_MATCHING"
ADD COLUMN "TYPE" smallint;
ALTER TABLE "APP"."CATEGORY_MATCHING"
ADD CONSTRAINT "CATEGORY_MATCHING_PKEY" PRIMARY KEY ("ID");
ALTER TABLE "APP"."CATEGORY_MATCHING"
ADD CONSTRAINT "APP_CATEGORY_MATCHING_ANALYSIS_TYPE_FKEY" FOREIGN KEY ("TYPE")
      REFERENCES "APP"."ANALYSIS_TYPE" ("ID")
      ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE "APP"."CATEGORY_ASSOCIATION" ALTER COLUMN "TYPE" SET NOT NULL;
ALTER TABLE "APP"."CATEGORY_MATCHING" ALTER COLUMN "TYPE" SET NOT NULL;

# --- !Downs

ALTER TABLE "APP"."CATEGORY_ASSOCIATION"
DROP CONSTRAINT "CATEGORY_ASSOCIATION_PKEY";
ALTER TABLE "APP"."CATEGORY_ASSOCIATION"
DROP COLUMN "TYPE";
ALTER TABLE "APP"."CATEGORY_ASSOCIATION"
DROP COLUMN "ID";
ALTER TABLE "APP"."CATEGORY_ASSOCIATION"
ADD CONSTRAINT "CATEGORY_ASSOCIATION_PKEY" PRIMARY KEY ("CATEGORY", "CATEGORY_RELATED");

ALTER TABLE "APP"."CATEGORY_MATCHING"
DROP CONSTRAINT "CATEGORY_MATCHING_PKEY";
ALTER TABLE "APP"."CATEGORY_MATCHING"
DROP COLUMN "TYPE";
ALTER TABLE "APP"."CATEGORY_MATCHING"
DROP COLUMN "ID";
ALTER TABLE "APP"."CATEGORY_MATCHING"
ADD CONSTRAINT "CATEGORY_MATCHING_PKEY" PRIMARY KEY ("CATEGORY", "CATEGORY_RELATED", "MATCHING_ALGORITHM");

ALTER TABLE "APP"."CATEGORY"
ADD COLUMN "COLLECTION_URI" character varying(500) NOT NULL DEFAULT '';
ALTER TABLE "APP"."CATEGORY"
ADD COLUMN "DRAFT_URI" character varying(500) NOT NULL DEFAULT '';
ALTER TABLE "APP"."CATEGORY"
ADD COLUMN "MIN_LOCUS_PER_PROFILE" character varying(1024) NOT NULL DEFAULT 'K';
ALTER TABLE "APP"."CATEGORY"
ADD COLUMN "MAX_SHORTAGE_DEVIATED_LOCI" character varying(1024) NOT NULL DEFAULT '0';
ALTER TABLE "APP"."CATEGORY"
ADD COLUMN "MAX_OVERAGE_DEVIATED_LOCI" character varying(1024) NOT NULL DEFAULT '0';

DROP TABLE "APP"."CATEGORY_CONFIGURATION";
