-- INSERTs del kit 'PowerplexFusion6C' generados el 2026-07-09T12:47:40+00:00 desde genisdb@localhost:5432
BEGIN;

INSERT INTO "APP"."STRKIT" ("ID", "NAME", "TYPE", "LOCI_QTY", "REPRESENTATIVE_PARAMETER") VALUES ('PowerplexFusion6C', 'PowerplexFusion6C', '1', '27', '26') ON CONFLICT ("ID") DO NOTHING;

INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'AMEL', NULL, '1') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'D3S1358', NULL, '2') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'D1S1656', NULL, '3') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'D2S441', NULL, '4') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'D10S1248', NULL, '5') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'D13S317', NULL, '6') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'PentaE', NULL, '7') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'D16S539', NULL, '8') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'D18S51', NULL, '9') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'D2S1338', NULL, '10') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'CSF1PO', NULL, '11') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'PentaD', NULL, '12') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'TH01', NULL, '13') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'vWA', NULL, '14') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'D21S11', NULL, '15') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'D7S820', NULL, '16') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'D5S818', NULL, '17') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'TPOX', NULL, '18') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'D8S1179', NULL, '19') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'D12S391', NULL, '20') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'D19S433', NULL, '21') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'ACTBP2', NULL, '22') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'D22S1045', NULL, '23') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'DYS391', NULL, '24') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'FGA', NULL, '25') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'DYS576', NULL, '26') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;
INSERT INTO "APP"."STRKIT_LOCUS" ("STRKIT", "LOCUS", "FLUOROPHORE", "ORDER") VALUES ('PowerplexFusion6C', 'DYS570', NULL, '27') ON CONFLICT ("STRKIT", "LOCUS") DO NOTHING;

COMMIT;
