INSERT INTO "APP"."PROFILE_RECEIVED" (
    "GLOBAL_CODE",
    "LABCODE",
    "STATUS",
    "MOTIVE",
    "USER",
    "IS_CATEGORY_MODIFICATION",
    "INTERCONNECTION_ERROR"
)
SELECT
    pd."GLOBAL_CODE",
    pd."INTERNAL_CODE" AS "LABCODE",
    CASE
        WHEN pd."DELETED" = TRUE THEN 19
        ELSE 18
        END AS "STATUS",
    CASE
        WHEN pd."DELETED_MOTIVE" IS NOT NULL THEN pd."DELETED_MOTIVE"
        ELSE NULL
        END AS "MOTIVE",
    NULL AS "USER",
    FALSE AS "IS_CATEGORY_MODIFICATION",
    NULL AS "INTERCONNECTION_ERROR"
FROM
    "APP"."PROFILE_DATA" pd
        JOIN
    "APP"."INFERIOR_INSTANCE" ii
    ON POSITION(ii."LABORATORY" IN pd."GLOBAL_CODE") > 0
WHERE
    (pd."DELETED" = FALSE OR pd."DELETED" IS NULL)
   OR
    (pd."DELETED" = TRUE);
