psql -U pdg -d pdgdb -c 'DELETE FROM "APP"."EXTERNAL_PROFILE_DATA"'
psql -U pdg -d pdgdb -c 'DELETE FROM "APP"."FILE_SENT"'
psql -U pdg -d pdgdb -c 'DELETE FROM "APP"."MATCH_SEND_STATUS"'
psql -U pdg -d pdgdb -c 'DELETE FROM "APP"."MATCH_UPDATE_SEND_STATUS"'
psql -U pdg -d pdgdb -c 'DELETE FROM "APP"."PEDCHECK"'
psql -U pdg -d pdgdb -c 'DELETE FROM "APP"."SUPERIOR_INSTANCE_PROFILE_APPROVAL"'
psql -U pdg -d pdgdb -c 'DELETE FROM "APP"."TRACE_PEDIGREE"'
psql -U pdg -d pdgdb -c 'DELETE FROM "APP"."NOTIFICATION"'
psql -U pdg -d pdgdb -c 'DELETE FROM "APP"."PEDIGREE"'
psql -U pdg -d pdgdb -c 'DELETE FROM "APP"."COURT_CASE_DATA_FILIATION"'
psql -U pdg -d pdgdb -c 'DELETE FROM "APP"."COURT_CASE_PROFILE"'
psql -U pdg -d pdgdb -c 'DELETE FROM "APP"."COURT_CASE"'
psql -U pdg -d pdgdb -c 'DELETE FROM "APP"."PROFILE_DATA_FILIATION_RESOURCES"'
psql -U pdg -d pdgdb -c 'DELETE FROM "APP"."PROFILE_DATA_FILIATION"'
psql -U pdg -d pdgdb -c 'DELETE FROM "APP"."PROFILE_UPLOADED"'
psql -U pdg -d pdgdb -c 'DELETE FROM "APP"."PROFILE_DATA_MOTIVE"'
psql -U pdg -d pdgdb -c 'DELETE FROM "APP"."PROFILE_SENT"'
psql -U pdg -d pdgdb -c 'DELETE FROM "APP"."PROFILE_DATA"'
psql -U pdg -d pdgdb -c 'DELETE FROM "APP"."TRACE"'
psql -U pdg -d pdgdb -c 'DELETE FROM "APP"."PROTO_PROFILE"'
psql -U pdg -d pdgdb -c 'DELETE FROM "APP"."BATCH_PROTO_PROFILE"'
psql -U pdg -d pdgdb -c 'DELETE FROM "APP"."LOCUS_ALLELE"'
psql -U pdg -d pdgdb -c 'DELETE FROM "STASH"."PROFILE_DATA_FILIATION_RESOURCES"'
psql -U pdg -d pdgdb -c 'DELETE FROM "STASH"."PROFILE_DATA_FILIATION"'
psql -U pdg -d pdgdb -c 'DELETE FROM "STASH"."PROFILE_DATA"'
mongo pdgdb --eval 'db.matches.remove({})'
mongo pdgdb --eval 'db.pedigreeMatches.remove({})'
mongo pdgdb --eval 'db.pedigrees.remove({})'
mongo pdgdb --eval 'db.electropherograms.remove({})'
mongo pdgdb --eval 'db.files.remove({})'
mongo pdgdb --eval 'db.scenarios.remove({})'
mongo pdgdb --eval 'db.profiles.remove({})'
mongo pdgdb --eval 'db.pedigreeGenotypification.remove({})'
mongo pdgdb --eval 'db.pedigreeScenarios.remove({})'
mongo pdgdb --eval 'db.collapsingMatches.remove({})'
mongo pdgdb --eval 'db.screeningMatches.remove({})'
