SELECT pg_catalog.setval('"APP"."CATEGORY_MATCHING_ID_seq"', (SELECT MAX("ID") FROM "APP"."CATEGORY_MATCHING"), true);
SELECT pg_catalog.setval('"APP"."CATEGORY_CONFIGURATION_ID_seq"', (SELECT MAX("ID") FROM "APP"."CATEGORY_CONFIGURATION"), true);
