package profiledata

// CD Removed unused imports: functionalCanBuildApplicative, toFunctionalBuilderOps, Reads, Writes, __
import play.api.libs.json.Format
import play.api.libs.json.Json
import types.SampleCode
import types.AlphanumericId
import java.util.Date

case class ProfileData(
  category: AlphanumericId,
  globalCode: SampleCode,
  attorney: Option[String],
  bioMaterialType: Option[String],
  court: Option[String],
  crimeInvolved: Option[String],
  crimeType: Option[String],
  criminalCase: Option[String],
  internalSampleCode: String,
  assignee: String,
  laboratory: String,
  deleted: Boolean,
  deletedMotive: Option[DeletedMotive],
  responsibleGeneticist: Option[String],
  profileExpirationDate: Option[Date],
  sampleDate: Option[Date],
  sampleEntryDate: Option[Date],
  dataFiliation: Option[DataFiliation],
  isExternal: Boolean)

object ProfileData {
  implicit val profiledataFormat: Format[ProfileData] = Json.format
}

case class ProfileDataFull(
  category: AlphanumericId,
  globalCode: SampleCode,
  attorney: Option[String],
  bioMaterialType: Option[String],
  court: Option[String],
  crimeInvolved: Option[String],
  crimeType: Option[String],
  criminalCase: Option[String],
  internalSampleCode: String,
  assignee: String,
  laboratory: String,
  deleted: Boolean,
  deletedMotive: Option[DeletedMotive],
  responsibleGeneticist: Option[String],
  profileExpirationDate: Option[Date],
  sampleDate: Option[Date],
  sampleEntryDate: Option[Date],
  dataFiliation: Option[DataFiliation],
  readOnly: Boolean = false,
  isExternal: Boolean)

object ProfileDataFull {
  implicit val profiledataFullFormat: Format[ProfileDataFull] = Json.format
}

case class ProfileDataAttempt(
  category: AlphanumericId,
  attorney: Option[String],
  bioMaterialType: Option[String],
  court: Option[String],
  crimeInvolved: Option[String],
  crimeType: Option[String],
  criminalCase: Option[String],
  internalSampleCode: String,
  assignee: String,
  laboratory: Option[String],
  responsibleGeneticist: Option[Long],
  profileExpirationDate: Option[Date],
  sampleDate: Option[Date],
  sampleEntryDate: Option[Date],
  dataFiliation: Option[DataFiliationAttempt]) {

  // CD
  // TODO: globalCode is set to a sentinel value here because the real globalCode
  // is generated by the repository (via DB sequence) after insertion.
  // This conversion should be revisited when the repository is migrated:
  // options are (a) make globalCode Option[SampleCode] in ProfileData,
  // or (b) split ProfileDataAttempt and ProfileData more explicitly
  // so this conversion never produces an incomplete ProfileData.
  // "XX-X-UNKNOWN-0" satisfies SampleCode.validationRe as a placeholder.
  def pdAttempToPd(labCode: String): ProfileData =
    ProfileData(
      this.category,
      SampleCode("XX-X-UNKNOWN-0"),
      this.attorney,
      this.bioMaterialType,
      this.court,
      this.crimeInvolved,
      this.crimeType,
      this.criminalCase,
      this.internalSampleCode,
      this.assignee,
      this.laboratory.getOrElse(labCode),
      false,
      None,
      this.responsibleGeneticist.map(_.toString),
      this.profileExpirationDate,
      this.sampleDate,
      this.sampleEntryDate,
      this.dataFiliation.map(_.dfAttempToDf),
      false)
}

object ProfileDataAttempt {
  implicit val profileAttemptFormat: Format[ProfileDataAttempt] = Json.format
}

case class ProfileDataWithBatch(
  category: AlphanumericId,
  globalCode: SampleCode,
  attorney: Option[String],
  bioMaterialType: Option[String],
  court: Option[String],
  crimeInvolved: Option[String],
  crimeType: Option[String],
  criminalCase: Option[String],
  internalSampleCode: String,
  assignee: String,
  laboratory: String,
  deleted: Boolean,
  deletedMotive: Option[DeletedMotive],
  responsibleGeneticist: Option[String],
  profileExpirationDate: Option[Date],
  sampleDate: Option[Date],
  sampleEntryDate: Option[Date],
  dataFiliation: Option[DataFiliation],
  label: Option[String])

object ProfileDataWithBatch {
  // CD
  // TODO: name clash with ProfileData.profiledataFormat in the same package —
  // both use the name `profiledataFormat`. Scala 3 does not complain at definition
  // time but can cause ambiguity at implicit resolution. Rename one of them once
  // the service layer is being wired up.
  implicit val profiledataFormat: Format[ProfileDataWithBatch] = Json.format
}

case class ProfileDataViewCoincidencia(
  globalCode: SampleCode,
  category: String,
  internalSampleCode: String,
  assignee: String,
  lastMatch: Date,
  hit: Int,
  pending: Int,
  descarte: Int)

object ProfileDataViewCoincidencia {
  implicit val profiledataViewCoincidenciaFormat: Format[ProfileDataViewCoincidencia] = Json.format
}