version: '3.8'
services:
  
  postgres:
    image: postgres:14.9
    container_name: genis_postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS="--auth=md5"
    ports:
      - "5455:5432"      
    volumes:
      - 'pgsql_data:/var/lib/postgresql/data'
      - ./pgsql_init:/docker-entrypoint-initdb.d
  
  openldap:
    image: osixia/openldap:latest
    container_name: genis_ldap
    restart: always
    ports:
      - '1389:389'
      - '1636:636'
    environment:
      - LDAP_ORGANISATION=Genis
      - LDAP_DOMAIN=genis.local
      - LDAP_ADMIN_PASSWORD=adminp
    volumes:
      - 'openldap_data:/var/lib/ldap'
      - 'slapd_data:/etc/ldap/slapd.d'
      - ./openldap_init:/ldifs        

  mongo:
    image: mongo:3.4.20
    container_name: genis_mongo
    restart: always    
    ports:
      - "27017:27017"      
    volumes:
      - 'mongo_data:/data/db'
      - ./mongo_init:/docker-entrypoint-initdb.d
  
  mongo-express:
    image: mongo-express:0.54.0
    container_name: genis_mongo-express
    restart: always    
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: genis_mongo

volumes:
  openldap_data:
    driver: local
  slapd_data:
    driver: local
  pgsql_data:
    driver: local
  mongo_data:
    driver: local    
